#!/usr/bin/env python3
"""Generate fr_to_cnr.json and apply Montenegrin translations to countries/me HTML."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
fr_de = json.loads((ROOT / "translations/fr_to_de.json").read_text(encoding="utf-8"))

CNR = {
    "Construction": "Gradnja",
    "Épaisseur totale": "Ukupna debljina",
    "Sélectionner": "Odaberite",
    "Lire →": "Pročitaj →",
    "Roumanie": "Rumunija",
    "étape par étape.": "korak po korak.",
    "Murs · MBK": "Zidovi · MBK",
    "Planchers · PBK": "Podovi · PBK",
    "Toit · TBK": "Krov · TBK",
    "Histoires": "Priče",
    "Toit": "Krov",
    "Murs": "Zidovi",
    "Comparaison": "Poređenje",
    "Isolation": "Izolacija",
    "Vos données sont confidentielles.": "Vaši podaci su povjerljivi.",
    "Délivré par :": "Izdaje:",
    "Télécharger le PDF": "Preuzmite PDF",
    "Devis": "Ponuda",
    "Télécharger la fiche technique": "Preuzmite tehnički list",
    "Caractéristique": "Karakteristika",
    "Portée maximale": "Maksimalni raspon",
    "Téléchargements": "Preuzimanja",
    "Documentation complète": "Kompletna dokumentacija",
    "Ajoutez le reste de la maison.": "Dodajte ostatak kuće.",
    "Commencer aujourd'hui": "Počnite danas",
    "Classe énergétique": "Energetska klasa",
    "Planchers": "Podovi",
    "Spécifications": "Specifikacije",
    "Localisation": "Lokacija",
    "Facture réelle électricité + gaz": "Stvarni račun za struju + gas",
    "Chronologie d'exécution": "Vremenski plan izvođenja",
    "De la fondation à": "Od temelja do",
    "la clé en main.": "ključ u ruke.",
    "Comment cela s'est passé": "Kako je proteklo",
    "Cliquez sur n'importe quelle image pour la voir en grand format.": "Kliknite na bilo koju sliku da je vidite u punoj veličini.",
    "Filtrer par étape.": "Filtrirajte po fazi.",
    "Voir l'étude de cas →": "Pogledajte studiju slučaja →",
    "Parlez-nous de votre projet.": "Recite nam o svom projektu.",
    "Mortier de maçonnerie": "Zidarski malter",
    "Mortier d'enduit": "Malter za fasadu",
    "Chevilles de fixation": "Tiplovi za fiksiranje",
    "Treillis de fibre": "Staklena mrežica",
    "Colle de façade": "Ljepilo za fasadu",
    "Convaincu par": "Uvjereni u",
    "France": "Francuska",
    "Joignez plans, croquis ou documents": "Priložite planove, skice ili dokumente",
    "Ingénieurs, architectes, designers et spécialistes en construction passive.": "Inženjeri, arhitekti, dizajneri i specijalisti za pasivnu gradnju.",
    "Les personnes qui font fonctionner le système Polistibrick sur trois continents.": "Ljudi koji pokreću Polistibrick sistem na tri kontinenta.",
    "Surface :": "Površina:",
    "Pays de présence": "Zemlje prisustva",
    "Innovation brevetée": "Patentirana inovacija",
    "Support technique sur chantier": "Tehnička podrška na gradilištu",
    "Tarifs préférentiels": "Povlašćene cijene",
    "Brique classique": "Klasična cigla",
    "Construction initiale": "Početna gradnja",
    "Architectes": "Arhitekti",
    "Cours de certification": "Kursevi certifikacije",
    "Résistance au feu": "Otpornost na vatru",
    "Pour": "Za",
    "Portées de 9 m sans poutres": "Rasponi od 9 m bez greda",
    "Exécution": "Izvođenje",
    "Comment ça fonctionne": "Kako funkcioniše",
    "Angles": "Uglovi",
    "Murs passifs A+++ en une seule coulée.": "Pasivni zidovi A+++ u jednom betoniranju.",
    "Garantie 50+ ans.": "Garancija 50+ godina.",
    "Spécifications techniques complètes": "Kompletne tehničke specifikacije",
    "Certificats CE + ETA": "CE + ETA certifikati",
    "Système Passivhaus sorti d'usine.": "Passivhaus sistem iz fabrike.",
    "Surface construite": "Izgrađena površina",
    "Exécution Polistibrick": "Izvođenje Polistibrick",
    "Surface utile": "Korisna površina",
    "Coût total (clé en main)": "Ukupni trošak (ključ u ruke)",
    "Semaine 1": "Sedmica 1",
    "Semaine 2": "Sedmica 2",
    "Semaine 3": "Sedmica 3",
    "Semaine 4": "Sedmica 4",
    "Produits": "Proizvodi",
    "Solutions": "Rješenja",
    "Projets": "Projekti",
    "Calculateur": "Kalkulator",
    "Ressources": "Resursi",
    "À propos": "O nama",
    "Contact": "Kontakt",
    "Demander un devis": "Zatražite ponudu",
    "Murs MBK": "Zidovi MBK",
    "Planchers PBK": "Podovi PBK",
    "Toit TBK": "Krov TBK",
    "Accessoires": "Pribor",
    "Pour les propriétaires": "Za vlasnike",
    "Pour les architectes": "Za arhitekte",
    "Pour les constructeurs": "Za građevince",
    "Pour les investisseurs": "Za investitore",
    "→ Devenez partenaire": "→ Postanite partner",
    "Maisons construites": "Izgrađene kuće",
    "Témoignages (vidéo)": "Svjedočanstva (video)",
    "Calculateur de coût": "Kalkulator troškova",
    "Calculateur d'économies (vs brique)": "Kalkulator ušteda (naspram cigle)",
    "Calculateur d'économies": "Kalkulator ušteda",
    "Questions fréquentes": "Često postavljana pitanja",
    "L'entreprise": "Kompanija",
    "Brevet": "Patent",
    "Certifications": "Sertifikati",
    "Nos usines": "Naše fabrike",
    "Le fondateur": "Osnivač",
    "Changer de pays": "Promijeni zemlju",
    "Navigation du site": "Navigacija sajta",
    "Propriétaires": "Vlasnici",
    "Constructeurs": "Građevinci",
    "Investisseurs": "Investitori",
    "Entreprise": "Kompanija",
    "Conditions": "Uslovi",
    "Mentions légales": "Pravne napomene",
    "Confidentialité": "Privatnost",
    "Cookies": "Kolačići",
    "Développement durable": "Održivost",
    "Tous droits réservés. Système breveté.": "Sva prava zadržana. Patentirani sistem.",
    "Choisissez votre pays": "Odaberite svoju zemlju",
    "Fermer": "Zatvori",
    "Accepter": "Prihvati",
    "Refuser": "Odbij",
    "Devis gratuit": "Besplatna ponuda",
    "Demander une offre": "Zatražite ponudu",
    "En savoir plus": "Saznajte više",
    "Voir la vidéo": "Pogledajte video",
    "Voir le projet →": "Pogledajte projekat →",
    "Voir tous les projets →": "Pogledajte sve projekte →",
    "Voir tous les témoignages →": "Pogledajte sva svjedočanstva →",
    "Envoyer": "Pošalji",
    "Envoyer le message": "Pošaljite poruku",
    "Nom": "Ime",
    "Prénom": "Ime",
    "Email": "E-mail",
    "Téléphone": "Telefon",
    "Message": "Poruka",
    "Sujet": "Predmet",
    "Pays": "Zemlja",
    "Ville": "Grad",
    "Adresse": "Adresa",
    "Oui": "Da",
    "Non": "Ne",
    "Retour": "Nazad",
    "Suivant": "Sljedeće",
    "Précédent": "Prethodno",
    "Fermer la vidéo": "Zatvorite video",
    "Chargement…": "Učitavanje…",
    "Erreur": "Greška",
    "Merci": "Hvala",
    "Gratuit": "Besplatno",
    "Gratuite": "Besplatna",
    "Sans compromis": "Bez kompromisa",
    "Maison passive": "Pasivna kuća",
    "Système ICF": "ICF sistem",
    "Système ICF breveté": "Patentirani ICF sistem",
    "Passivhaus": "Passivhaus",
    "Économies": "Uštede",
    "Économie": "Ušteda",
    "Montage": "Montaža",
    "Installation": "Montaža",
    "Blog": "Blog",
    "FAQ": "FAQ",
    "Partenaire": "Partner",
    "Partenaires": "Partneri",
    "Devenez partenaire": "Postanite partner",
    "Témoignages": "Svjedočanstva",
    "Témoignage": "Svjedočanstvo",
    "Projets réalisés": "Realizovani projekti",
    "Galerie": "Galerija",
    "Vidéo": "Video",
    "Photos": "Fotografije",
    "Télécharger": "Preuzmite",
    "Documentation": "Dokumentacija",
    "Fiche technique": "Tehnički list",
    "Patent": "Patent",
    "Brevet Polistibrick": "Polistibrick patent",
    "Le brevet Polistibrick": "Polistibrick patent",
    "Notre histoire": "Naša priča",
    "Notre mission": "Naša misija",
    "Notre vision": "Naša vizija",
    "Qui sommes-nous": "Ko smo mi",
    "L'équipe": "Tim",
    "Fondateur": "Osnivač",
    "Usines": "Fabrike",
    "Fabrique": "Fabrika",
    "Valence": "Valencija",
    "Espagne": "Španija",
    "Italie": "Italija",
    "Belgique": "Belgija",
    "Irlande": "Irska",
    "Royaume-Uni": "Ujedinjeno Kraljevstvo",
    "Suisse": "Švicarska",
    "Allemagne": "Njemačka",
    "Autriche": "Austrija",
    "Pays-Bas": "Holandija",
    "Montenegro": "Crna Gora",
    "Redirection vers": "Preusmjeravanje na",
    "Je reste ici": "Ostajem ovdje",
    "Da, mergi": "Da, idi",
    "Nous détectons que vous êtes en": "Detektujemo da ste u",
    "Vizitezi": "Posjećujete",
    "politique de confidentialité": "politika privatnosti",
    "politique de cookies": "politika kolačića",
    "Consentement cookies": "Saglasnost za kolačiće",
    "Nous utilisons des cookies": "Koristimo kolačiće",
    "Appeler": "Pozovite",
    "Envoyer un email": "Pošaljite e-mail",
    "Contact rapide": "Brzi kontakt",
    "Appeler Polistibrick": "Pozovite Polistibrick",
    "E-mail": "E-mail",
    "Année": "Godina",
    "Années": "Godine",
    "Mois": "Mjesec",
    "Semaines": "Sedmice",
    "Jours": "Dani",
    "Heures": "Sati",
    "Coût": "Trošak",
    "Prix": "Cijena",
    "Total": "Ukupno",
    "Estimation": "Procjena",
    "Estimez": "Procijenite",
    "Calculez": "Izračunajte",
    "Comparer": "Uporedite",
    "Comparatif": "Poređenje",
    "Avantages": "Prednosti",
    "Avantage": "Prednost",
    "Inconvénients": "Nedostaci",
    "Performance": "Performanse",
    "Performances": "Performanse",
    "Thermique": "Termički",
    "Acoustique": "Akustički",
    "Étanchéité": "Hidroizolacija",
    "Durabilité": "Trajnost",
    "Écologique": "Ekološki",
    "Durable": "Održivo",
    "Recyclable": "Reciklabilno",
    "Carbone": "Ugljenik",
    "Énergie": "Energija",
    "Facture": "Račun",
    "Factures": "Računi",
    "Consommation": "Potrošnja",
    "Chauffage": "Grijanje",
    "Climatisation": "Klimatizacija",
    "Ventilation": "Ventilacija",
    "Isolation thermique": "Termička izolacija",
    "Ponts thermiques": "Termički mostovi",
    "Étanchéité à l'air": "Nepropusnost vazduha",
    "Test Blower Door": "Blower Door test",
    "Certification": "Certifikacija",
    "Certifié": "Certificirano",
    "Norme": "Norma",
    "Normes": "Norme",
    "Standard": "Standard",
    "Conformité": "Usaglašenost",
    "Agrément": "Odobrenje",
    "Agréments": "Odobrenja",
    "Marquage CE": "CE označavanje",
    "Garantie": "Garancija",
    "Garanties": "Garancije",
    "Assurance": "Osiguranje",
    "Responsabilité": "Odgovornost",
    "Qualité": "Kvalitet",
    "Contrôle qualité": "Kontrola kvaliteta",
    "Production": "Proizvodnja",
    "Fabrication": "Proizvodnja",
    "Préfabrication": "Prefabrikacija",
    "Préfabriqué": "Prefabrikovano",
    "Sur chantier": "Na gradilištu",
    "Chantier": "Gradilište",
    "Fondations": "Temelji",
    "Fondation": "Temelj",
    "Dalle": "Ploča",
    "Plancher": "Pod",
    "Plafond": "Plafon",
    "Mur": "Zid",
    "Façade": "Fasada",
    "Toiture": "Krov",
    "Charpente": "Krovna konstrukcija",
    "Couverture": "Pokrivač",
    "Fenêtre": "Prozor",
    "Fenêtres": "Prozori",
    "Porte": "Vrata",
    "Escalier": "Stepenice",
    "Escaliers": "Stepenice",
    "Béton": "Beton",
    "Coulée": "Betonaža",
    "Coffrage": "Oplata",
    "Coffrage isolant": "Izolaciona oplata",
    "Panneau": "Panel",
    "Panneaux": "Paneli",
    "Module": "Modul",
    "Modules": "Moduli",
    "Kit": "Kit",
    "Système complet": "Kompletan sistem",
    "Enveloppe": "Omotač",
    "Enveloppe du bâtiment": "Omotač zgrade",
    "Bâtiment": "Zgrada",
    "Maison": "Kuća",
    "Maisons": "Kuće",
    "Villa": "Vila",
    "Villas": "Vile",
    "Résidence": "Rezidencija",
    "Logement": "Stan",
    "Logements": "Stanovi",
    "Appartement": "Stan",
    "Immeuble": "Zgrada",
    "Ensemble": "Kompleks",
    "Lotissement": "Parcela",
    "Promotion immobilière": "Građevinska investicija",
    "Investissement": "Investicija",
    "Investisseur": "Investitor",
    "Promoteur": "Investitor",
    "Architecte": "Arhitekt",
    "Ingénieur": "Inženjer",
    "Bureau d'études": "Projektantski biro",
    "Constructeur": "Građevinac",
    "Entrepreneur": "Preduzetnik",
    "Artisan": "Majstor",
    "Propriétaire": "Vlasnik",
    "Particulier": "Pojedinac",
    "Client": "Klijent",
    "Clients": "Klijenti",
    "Partenaire certifié": "Certificirani partner",
    "Réseau de partenaires": "Mreža partnera",
    "Formation": "Obuka",
    "Support technique": "Tehnička podrška",
    "Assistance": "Podrška",
    "Service client": "Korisnička podrška",
    "Demande de devis": "Zahtjev za ponudu",
    "Demande de documentation": "Zahtjev za dokumentaciju",
    "Support produit": "Podrška za proizvod",
    "Autre": "Ostalo",
    "Sélectionnez": "Odaberite",
    "Votre nom": "Vaše ime",
    "Votre prénom": "Vaše ime",
    "Votre email": "Vaš e-mail",
    "Votre message": "Vaša poruka",
    "Comment pouvons-nous vous aider ?": "Kako vam možemo pomoći?",
    "Message envoyé": "Poruka poslata",
    "Merci !": "Hvala!",
    "Notre équipe vous répond sous 24 heures ouvrées.": "Naš tim vam odgovara u roku od 24 radna sata.",
    "J'accepte": "Prihvatam",
    "politique de confidentialité (RGPD)": "politika privatnosti (GDPR)",
    "Vous êtes": "Vi ste",
    "Bureau d'études (BET)": "Projektantski biro",
    "Constructeur / Entrepreneur": "Građevinac / preduzetnik",
    "Particulier / Propriétaire": "Pojedinac / vlasnik",
    "Promoteur / Investisseur": "Investitor",
    "Écrivez-nous directement.": "Pišite nam direktno.",
    "Des spécialistes à un clic.": "Stručnjaci na klik.",
    "Sélectionnez le pays": "Odaberite zemlju",
    "Siège": "Sjedište",
    "En ligne": "Online",
    "Supprimer": "Ukloni",
    "Le fichier": "Datoteka",
    "est trop volumineux": "je prevelika",
    "Maximum 10 MB par fichier.": "Maksimalno 10 MB po datoteci.",
    "Bonjour,": "Zdravo,",
    "Merci d'avance.": "Hvala unaprijed.",
    "Une maison. Un système. Sans compromis.": "Jedna kuća. Jedan sistem. Bez kompromisa.",
    "Une maison. Un système.": "Jedna kuća. Jedan sistem.",
    "Système ICF complet — murs, planchers, toit. standard A+++. Construit en 4 semaines. Sans compromis, sans factures.": "Kompletan ICF sistem — zidovi, podovi, krov. standard A+++. Izgrađeno za 4 sedmice. Bez kompromisa, bez računa.",
    "Système ICF complet pour maison A+++. Murs, planchers, toit — un système premium.": "Kompletan ICF sistem za kuću A+++. Zidovi, podovi, krov — premium sistem.",
    "Coffrage isolant pour murs porteurs": "Izolaciona oplata za noseće zidove",
    "Panneaux préfabriqués avec déphasage 10,8 h": "Prefabrikovani paneli sa faznim pomakom 10,8 h",
    "Maison passive sans grosses factures": "Pasivna kuća bez visokih računa",
    "Détails constructifs, BIM, fiches": "Konstruktivni detalji, BIM, listovi",
    "Pose, certification, partenariat": "Montaža, certifikacija, partnerstvo",
    "ROI, rapidité d'exécution, ensembles": "ROI, brzina izvođenja, kompleksi",
    "Candidature constructeurs certifiés": "Prijava certificiranih građevinaca",
    "Galerie + carte des projets": "Galerija + mapa projekata",
    "Les propriétaires parlent, avec des chiffres réels": "Vlasnici govore, sa stvarnim brojkama",
    "Estimez le prix des panneaux pour votre maison": "Procijenite cijenu panela za vašu kuću",
    "Polistibrick vs brique sur 25 ans": "Polistibrick naspram cigle za 25 godina",
    "Articles sur la Maison Passive, l'ICF": "Članci o pasivnoj kući, ICF-u",
    "Réponses aux questions les plus courantes": "Odgovori na najčešća pitanja",
    "Qui nous sommes, vision, mission": "Ko smo mi, vizija, misija",
    "Le brevet qui nous rend uniques": "Patent koji nas čini jedinstvenim",
    "CE, ISO, Passivhaus, agréments": "CE, ISO, Passivhaus, odobrenja",
    "Valence (ES) et Craiova (RO)": "Valencija (ES) i Krajova (RO)",
    "Fondateurs et nos collaborateurs": "Osnivači i naši saradnici",
    "Le système ICF breveté pour maisons passives haut de gamme, sans factures d'énergie. Fabriqué dans l'UE.": "Patentirani ICF sistem za premium pasivne kuće, bez računa za energiju. Proizvedeno u EU.",
    "Termes": "Uslovi",
    "Informations légales": "Pravne informacije",
    "Tous droits réservés.": "Sva prava zadržana.",
    "Dans quel pays": "U kojoj zemlji",
    "construisez-vous ?": "gradite?",
    "Nous vous redirigeons vers le site de votre pays avec l'équipe locale, un contact direct et un devis dans votre langue.": "Preusmjeravamo vas na sajt vaše zemlje sa lokalnim timom, direktnim kontaktom i ponudom na vašem jeziku.",
    "Votre pays": "Vaša zemlja",
    "Votre pays n'est pas listé ? Écrivez-nous à": "Vaša zemlja nije na listi? Pišite nam na",
    "Polistibrick — Construction intelligente": "Polistibrick — Pametna gradnja",
    "Polistibrick vs système classique vs autre ICF": "Polistibrick naspram klasičnog sistema naspram drugog ICF-a",
    "Navigation principale": "Glavna navigacija",
    "Ouvrir le menu": "Otvorite meni",
    "Menu de navigation": "Meni navigacije",
    "Polistibrick — accueil": "Polistibrick — početna",
    "Angles, embouts, escaliers, fenêtres": "Uglovi, završeci, stepenice, prozori",
}

WORD_MAP = [
    ("témoignages", "svjedočanstva"), ("Témoignages", "Svjedočanstva"), ("témoignage", "svjedočanstvo"),
    ("propriétaires", "vlasnici"), ("Propriétaires", "Vlasnici"), ("propriétaire", "vlasnik"),
    ("constructeurs", "građevinci"), ("Constructeurs", "Građevinci"), ("constructeur", "građevinac"),
    ("investisseurs", "investitori"), ("Investisseurs", "Investitori"), ("investisseur", "investitor"),
    ("architectes", "arhitekti"), ("Architectes", "Arhitekti"), ("architecte", "arhitekt"),
    ("maisons", "kuće"), ("Maisons", "Kuće"), ("maison", "kuća"), ("Maison", "Kuća"),
    ("murs", "zidovi"), ("Murs", "Zidovi"), ("mur", "zid"), ("Mur", "Zid"),
    ("planchers", "podovi"), ("Planchers", "Podovi"), ("plancher", "pod"), ("Plancher", "Pod"),
    ("toit", "krov"), ("Toit", "Krov"), ("toiture", "krov"), ("Toiture", "Krov"),
    ("devis", "ponuda"), ("Devis", "Ponuda"),
    ("contact", "kontakt"), ("Contact", "Kontakt"),
    ("projets", "projekti"), ("Projets", "Projekti"), ("projet", "projekat"), ("Projet", "Projekat"),
    ("ressources", "resursi"), ("Ressources", "Resursi"),
    ("produits", "proizvodi"), ("Produits", "Proizvodi"), ("produit", "proizvod"), ("Produit", "Proizvod"),
    ("solutions", "rješenja"), ("Solutions", "Rješenja"),
    ("calculateur", "kalkulator"), ("Calculateur", "Kalkulator"),
    ("certifications", "sertifikati"), ("Certifications", "Sertifikati"),
    ("usines", "fabrike"), ("Usines", "Fabrike"), ("usine", "fabrika"), ("Usine", "Fabrika"),
    ("brevet", "patent"), ("Brevet", "Patent"),
    ("fondateur", "osnivač"), ("Fondateur", "Osnivač"),
    ("entreprise", "kompanija"), ("Entreprise", "Kompanija"), ("L'entreprise", "Kompanija"),
    ("économies", "uštede"), ("Économies", "Uštede"), ("économie", "ušteda"), ("Économie", "Ušteda"),
    ("gratuit", "besplatno"), ("Gratuit", "Besplatno"), ("gratuite", "besplatna"), ("Gratuite", "Besplatna"),
    ("demander", "zatražite"), ("Demander", "Zatražite"),
    ("en savoir plus", "saznajte više"), ("En savoir plus", "Saznajte više"),
    ("voir", "pogledajte"), ("Voir", "Pogledajte"),
    ("télécharger", "preuzmite"), ("Télécharger", "Preuzmite"),
    ("envoyer", "pošaljite"), ("Envoyer", "Pošaljite"),
    ("sélectionner", "odaberite"), ("Sélectionner", "Odaberite"), ("Sélectionnez", "Odaberite"),
    ("questions fréquentes", "često postavljana pitanja"), ("Questions fréquentes", "Često postavljana pitanja"),
    ("à propos", "o nama"), ("À propos", "O nama"),
    ("pour les", "za"), ("Pour les", "Za"),
    ("devenez partenaire", "postanite partner"), ("Devenez partenaire", "Postanite partner"),
    ("mentions légales", "pravne napomene"), ("Mentions légales", "Pravne napomene"),
    ("confidentialité", "privatnost"), ("Confidentialité", "Privatnost"),
    ("développement durable", "održivost"), ("Développement durable", "Održivost"),
    ("montage", "montaža"), ("Montage", "Montaža"),
    ("isolation", "izolacija"), ("Isolation", "Izolacija"),
    ("spécifications", "specifikacije"), ("Spécifications", "Specifikacije"),
    ("documentation", "dokumentacija"), ("Documentation", "Dokumentacija"),
    ("garantie", "garancija"), ("Garantie", "Garancija"),
    ("facture", "račun"), ("Facture", "Račun"), ("factures", "računi"), ("Factures", "Računi"),
    ("énergie", "energija"), ("Énergie", "Energija"),
    ("chauffage", "grijanje"), ("Chauffage", "Grijanje"),
    ("consommation", "potrošnja"), ("Consommation", "Potrošnja"),
    ("coût", "trošak"), ("Coût", "Trošak"), ("coûts", "troškovi"), ("Coûts", "Troškovi"),
    ("prix", "cijena"), ("Prix", "Cijena"),
    ("comparaison", "poređenje"), ("Comparaison", "Poređenje"),
    ("avantages", "prednosti"), ("Avantages", "Prednosti"),
    ("durabilité", "trajnost"), ("Durabilité", "Trajnost"),
    ("qualité", "kvalitet"), ("Qualité", "Kvalitet"),
    ("fabrication", "proizvodnja"), ("Fabrication", "Proizvodnja"),
    ("panneaux", "paneli"), ("Panneaux", "Paneli"), ("panneau", "panel"), ("Panneau", "Panel"),
    ("béton", "beton"), ("Béton", "Beton"),
    ("coffrage", "oplata"), ("Coffrage", "Oplata"),
    ("chantier", "gradilište"), ("Chantier", "Gradilište"),
    ("fondations", "temelji"), ("Fondations", "Temelji"),
    ("façade", "fasada"), ("Façade", "Fasada"),
    ("fenêtres", "prozori"), ("Fenêtres", "Prozori"), ("fenêtre", "prozor"), ("Fenêtre", "Prozor"),
    ("escaliers", "stepenice"), ("Escaliers", "Stepenice"),
    ("partenaire", "partner"), ("Partenaire", "Partner"), ("partenaires", "partneri"),
    ("formation", "obuka"), ("Formation", "Obuka"),
    ("support", "podrška"), ("Support", "Podrška"),
    ("message", "poruka"), ("Message", "Poruka"),
    ("nom", "ime"), ("Nom", "Ime"),
    ("téléphone", "telefon"), ("Téléphone", "Telefon"),
    ("adresse", "adresa"), ("Adresse", "Adresa"),
    ("ville", "grad"), ("Ville", "Grad"),
    ("pays", "zemlja"), ("Pays", "Zemlja"),
    ("merci", "hvala"), ("Merci", "Hvala"),
    ("fermer", "zatvori"), ("Fermer", "Zatvori"),
    ("accepter", "prihvati"), ("Accepter", "Prihvati"),
    ("refuser", "odbij"), ("Refuser", "Odbij"),
    ("année", "godina"), ("Année", "Godina"), ("années", "godine"), ("Années", "Godine"),
    ("semaine", "sedmica"), ("Semaine", "Sedmica"), ("semaines", "sedmice"), ("Semaines", "Sedmice"),
    ("système", "sistem"), ("Système", "Sistem"),
    ("breveté", "patentiran"), ("brevetée", "patentirana"),
    ("sans compromis", "bez kompromisa"), ("Sans compromis", "Bez kompromisa"),
    ("clé en main", "ključ u ruke"),
    ("exécution", "izvođenje"), ("Exécution", "Izvođenje"),
    ("surface", "površina"), ("Surface", "Površina"),
    ("brique", "cigla"), ("Brique", "Cigla"),
    ("roumanie", "Rumunija"), ("Roumanie", "Rumunija"),
    ("france", "Francuska"), ("France", "Francuska"),
    ("espagne", "Španija"), ("Espagne", "Španija"),
    ("italie", "Italija"), ("Italie", "Italija"),
    ("belgique", "Belgija"), ("Belgique", "Belgija"),
    ("irlande", "Irska"), ("Irlande", "Irlanda"),
    ("allemagne", "Njemačka"), ("Allemagne", "Njemačka"),
    ("suisse", "Švicarska"), ("Suisse", "Švicarska"),
    ("autriche", "Austrija"), ("Autriche", "Austrija"),
    ("royaume-uni", "Ujedinjeno Kraljevstvo"), ("Royaume-Uni", "Ujedinjeno Kraljevstvo"),
    ("valence", "Valencija"), ("Valence", "Valencija"),
    ("craiova", "Krajova"), ("Craiova", "Krajova"),
    ("vidéo", "video"), ("Vidéo", "Video"),
    ("photos", "fotografije"), ("Photos", "Fotografije"),
    ("galerie", "galerija"), ("Galerie", "Galerija"),
    ("histoires", "priče"), ("Histoires", "Priče"),
    ("angles", "uglovi"), ("Angles", "Uglovi"),
    ("accessoires", "pribor"), ("Accessoires", "Pribor"),
    ("conditions", "uslovi"), ("Conditions", "Uslovi"),
    ("termes", "uslovi"), ("Termes", "Uslovi"),
    ("politique", "politika"), ("Politique", "Politika"),
    ("navigation", "navigacija"), ("Navigation", "Navigacija"),
    ("menu", "meni"), ("Menu", "Meni"),
    ("accueil", "početna"),
    ("choisissez", "odaberite"), ("Choisissez", "Odaberite"),
    ("votre", "vaš"), ("Votre", "Vaš"), ("vos", "vaši"), ("Vos", "Vaši"),
    ("notre", "naš"), ("Notre", "Naš"), ("nos", "naši"), ("Nos", "Naši"),
    ("nous", "mi"), ("Nous", "Mi"),
    ("vous", "vi"), ("Vous", "Vi"),
    ("avec", "sa"), ("Avec", "Sa"),
    ("pour", "za"), ("Pour", "Za"),
    ("sur", "na"), ("Sur", "Na"),
    ("dans", "u"), ("Dans", "U"),
    ("sans", "bez"), ("Sans", "Bez"),
    ("plus", "više"), ("Plus", "Više"),
    ("comment", "kako"), ("Comment", "Kako"),
    ("pourquoi", "zašto"), ("Pourquoi", "Zašto"),
    ("construire", "graditi"), ("construisez", "gradite"),
    ("construit", "izgrađeno"), ("Construit", "Izgrađeno"),
    ("construite", "izgrađena"), ("construites", "izgrađene"),
    ("réalisé", "realizovan"), ("réalisée", "realizovana"), ("réalisés", "realizovani"),
    ("certifié", "certificiran"), ("certifiée", "certificirana"), ("certifiés", "certificirani"),
    ("technique", "tehnički"), ("Technique", "Tehnički"), ("techniques", "tehničke"),
    ("thermique", "termički"), ("Thermique", "Termički"),
    ("durable", "održivo"), ("Durable", "Održivo"),
    ("passive", "pasivna"), ("passif", "pasivni"), ("passifs", "pasivni"),
    ("maison passive", "pasivna kuća"), ("Maison Passive", "Pasivna kuća"),
    ("ingénieur", "inženjer"), ("Ingénieur", "Inženjer"), ("ingénieurs", "inženjeri"),
    ("entrepreneur", "preduzetnik"), ("Entrepreneur", "Preduzetnik"),
    ("particulier", "pojedinac"), ("Particulier", "Pojedinac"),
    ("client", "klijent"), ("Client", "Klijent"), ("clients", "klijenti"),
    ("autre", "ostalo"), ("Autre", "Ostalo"),
    ("prénom", "ime"), ("Prénom", "Ime"),
    ("sujet", "predmet"), ("Sujet", "Predmet"),
    ("oui", "da"), ("Oui", "Da"), ("non", "ne"), ("Non", "Ne"),
    ("erreur", "greška"), ("Erreur", "Greška"),
    ("supprimer", "ukloni"), ("Supprimer", "Ukloni"),
    ("joignez", "priložite"), ("Joignez", "Priložite"),
    ("écrivez-nous", "pišite nam"), ("Écrivez-nous", "Pišite nam"),
    ("parlez-nous", "recite nam"), ("Parlez-nous", "Recite nam"),
    ("cliquez", "kliknite"), ("Cliquez", "Kliknite"),
    ("estimez", "procijenite"), ("Estimez", "Procijenite"),
    ("calculez", "izračunajte"), ("Calculez", "Izračunajte"),
    ("commencer", "počnite"), ("Commencer", "Počnite"),
    ("ajoutez", "dodajte"), ("Ajoutez", "Dodajte"),
    ("lisez", "pročitajte"), ("Lire", "Pročitaj"),
    ("découvrez", "otkrijte"), ("Découvrez", "Otkrijte"),
    ("consultez", "pogledajte"), ("Consultez", "Pogledajte"),
    ("fiche technique", "tehnički list"), ("Fiche technique", "Tehnički list"),
    ("caractéristique", "karakteristika"), ("Caractéristique", "Karakteristika"),
    ("mortier", "malter"), ("Mortier", "Malter"),
    ("innovation brevetée", "patentirana inovacija"),
    ("résistance au feu", "otpornost na vatru"),
    ("portées", "rasponi"), ("Portées", "Rasponi"),
    ("poutres", "grede"), ("Poutres", "Grede"),
    ("électricité", "struja"), ("Électricité", "Struja"),
    ("gaz", "gas"), ("Gaz", "Gas"),
    ("climatisation", "klimatizacija"), ("Climatisation", "Klimatizacija"),
    ("ventilation", "ventilacija"), ("Ventilation", "Ventilacija"),
    ("assurance", "osiguranje"), ("Assurance", "Osiguranje"),
    ("production", "proizvodnja"), ("Production", "Proizvodnja"),
    ("dalle", "ploča"), ("Dalle", "Ploča"),
    ("plafond", "plafon"), ("Plafond", "Plafon"),
    ("enveloppe", "omotač"), ("Enveloppe", "Omotač"),
    ("bâtiment", "zgrada"), ("Bâtiment", "Zgrada"),
    ("villa", "vila"), ("Villa", "Vila"),
    ("résidence", "rezidencija"), ("Résidence", "Rezidencija"),
    ("logement", "stan"), ("Logement", "Stan"), ("logements", "stanovi"),
    ("appartement", "stan"), ("Appartement", "Stan"),
    ("immeuble", "zgrada"), ("Immeuble", "Zgrada"),
    ("ensemble", "kompleks"), ("Ensemble", "Kompleks"),
    ("investissement", "investicija"), ("Investissement", "Investicija"),
    ("promoteur", "investitor"), ("Promoteur", "Investitor"),
    ("bureau d'études", "projektantski biro"),
    ("demande de devis", "zahtjev za ponudu"),
    ("demande de documentation", "zahtjev za dokumentaciju"),
    ("support produit", "podrška za proizvod"),
    ("message envoyé", "poruka poslata"),
    ("j'accepte", "prihvatam"), ("J'accepte", "Prihvatam"),
    ("vous êtes", "vi ste"), ("Vous êtes", "Vi ste"),
    ("siège", "sjedište"), ("Siège", "Sjedište"),
    ("en ligne", "online"), ("En ligne", "Online"),
    ("bonjour", "zdravo"), ("Bonjour", "Zdravo"),
    ("merci d'avance", "hvala unaprijed"),
    ("changer de pays", "promijeni zemlju"),
    ("consentement cookies", "saglasnost za kolačiće"),
    ("informations légales", "pravne informacije"),
    ("tous droits réservés", "sva prava zadržana"),
    ("système breveté", "patentirani sistem"),
    ("dans quel pays", "u kojoj zemlji"),
    ("construisez-vous", "gradite"),
    ("construction intelligente", "pametna gradnja"),
    ("système classique", "klasični sistem"),
    ("autre ICF", "drugi ICF"),
    ("navigation principale", "glavna navigacija"),
    ("ouvrir le menu", "otvorite meni"),
    ("menu de navigation", "meni navigacije"),
    ("embouts", "završeci"),
    ("déphasage", "fazni pomak"),
    ("détails constructifs", "konstruktivni detalji"),
    ("fiches", "listovi"),
    ("pose", "montaža"), ("Pose", "Montaža"),
    ("partenariat", "partnerstvo"), ("Partenariat", "Partnerstvo"),
    ("rapidité", "brzina"), ("Rapidité", "Brzina"),
    ("ensembles", "kompleksi"), ("Ensembles", "Kompleksi"),
    ("candidature", "prijava"), ("Candidature", "Prijava"),
    ("carte des projets", "mapa projekata"),
    ("chiffres réels", "stvarne brojke"),
    ("articles sur", "članci o"),
    ("réponses aux", "odgovori na"),
    ("questions les plus courantes", "najčešća pitanja"),
    ("qui nous sommes", "ko smo mi"),
    ("vision", "vizija"), ("Vision", "Vizija"),
    ("mission", "misija"), ("Mission", "Misija"),
    ("collaborateurs", "saradnici"),
    ("factures d'énergie", "računi za energiju"),
    ("fabriqué dans l'UE", "proizvedeno u EU"),
    ("fabriqué", "proizvedeno"), ("Fabriqué", "Proizvedeno"),
    ("haut de gamme", "premium"),
    ("sortie d'usine", "iz fabrike"),
    ("sorti d'usine", "iz fabrike"),
    ("une seule coulée", "jednom betoniranju"),
    ("murs porteurs", "noseći zidovi"),
    ("coffrage isolant", "izolaciona oplata"),
    ("panneaux préfabriqués", "prefabrikovani paneli"),
    ("grosses factures", "visoki računi"),
    ("de la fondation à", "od temelja do"),
    ("la clé en main", "ključ u ruke"),
    ("étape par étape", "korak po korak"),
    ("étude de cas", "studija slučaja"),
    ("filtrer par étape", "filtrirajte po fazi"),
    ("grand format", "punoj veličini"),
    ("n'importe quelle", "bilo koju"),
    ("s'est passé", "je proteklo"),
    ("isolation thermique", "termička izolacija"),
    ("ponts thermiques", "termički mostovi"),
    ("étanchéité à l'air", "nepropusnost vazduha"),
    ("préfabrication", "prefabrikacija"), ("Préfabrication", "Prefabrikacija"),
    ("préfabriqué", "prefabrikovano"), ("Préfabriqué", "Prefabrikovano"),
    ("charpente", "krovna konstrukcija"), ("Charpente", "Krovna konstrukcija"),
    ("couverture", "pokrivač"), ("Couverture", "Pokrivač"),
    ("porte", "vrata"), ("Porte", "Vrata"),
    ("escalier", "stepenice"), ("Escalier", "Stepenice"),
    ("coulée", "betonaža"), ("Coulée", "Betonaža"),
    ("module", "modul"), ("Module", "Modul"), ("modules", "moduli"),
    ("lotissement", "parcela"), ("Lotissement", "Parcela"),
    ("réseau de partenaires", "mreža partnera"),
    ("partenaire certifié", "certificirani partner"),
    ("des spécialistes", "stručnjaci"),
    ("à un clic", "na klik"),
    ("est trop volumineux", "je prevelika"),
    ("maximum 10 MB", "maksimalno 10 MB"),
    ("par fichier", "po datoteci"),
    ("contactez-nous", "kontaktirajte nas"),
    ("via la page", "preko stranice"),
    ("page Contact", "stranica Kontakt"),
]


def translate_fr_to_cnr(fr_text: str) -> str:
    if fr_text in CNR:
        return CNR[fr_text]
    result = fr_text
    for old, new in sorted(WORD_MAP, key=lambda x: -len(x[0])):
        result = result.replace(old, new)
    return result


def build_fr_to_cnr() -> dict:
    fr_to_cnr = {}
    for fr_key in fr_de:
        cnr_val = translate_fr_to_cnr(fr_key)
        if fr_key != cnr_val:
            fr_to_cnr[fr_key] = cnr_val
    fr_to_cnr.update({k: v for k, v in CNR.items() if k != v})
    return fr_to_cnr


def apply_to_html(fr_to_cnr: dict) -> int:
    me_dir = ROOT / "countries/me"
    pairs = sorted(fr_to_cnr.items(), key=lambda x: -len(x[0]))
    changed = 0
    for html in sorted(me_dir.rglob("*.html")):
        text = html.read_text(encoding="utf-8")
        orig = text
        for fr, cnr in pairs:
            text = text.replace(fr, cnr)
        if text != orig:
            html.write_text(text, encoding="utf-8")
            changed += 1
    return changed


def main():
    fr_to_cnr = build_fr_to_cnr()
    out_path = ROOT / "translations/fr_to_cnr.json"
    out_path.write_text(
        json.dumps(dict(sorted(fr_to_cnr.items())), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"Wrote {len(fr_to_cnr)} pairs to {out_path}")
    n = apply_to_html(fr_to_cnr)
    print(f"Updated {n} HTML files")


if __name__ == "__main__":
    main()
