#!/usr/bin/env python3
"""Fourth pass: safe multi-word RO→CNR + remaining French visible text."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent / "countries/me"

# Phrase-level (longest first) — safe substring replace
PHRASES = [
    ("Pentru investitori și dezvoltatori · Polistibrick — Ansambluri rezidențiale pasive",
     "Za investitore i developere · Polistibrick — Pasivni stambeni kompleksi"),
    ("Polistibrick pentru dezvoltatori și investitori: +15–25% primă la revânzare, structură de 3× mai rapidă, tarife de volum de la 5 unități, acord-cadru dedicat. Maximizați marja, minimizați riscul.",
     "Polistibrick za developere i investitore: +15–25% premija pri preprodaji, struktura 3× brža, volumske cijene od 5 jedinica, posvećeni okvirni ugovor. Maksimizujte maržu, minimizujte rizik."),
    ("Pentru investitori și dezvoltatori", "Za investitore i developere"),
    ("Za investitore i dezvoltatori", "Za investitore i developere"),
    ("Construiește mai repede. <em>Vinde mai scump. Risc redus.</em>",
     "Gradite brže. <em>Prodajte skuplje. Smanjen rizik.</em>"),
    ("Polistibrick pentru ansambluri rezidențiale:", "Polistibrick za stambene komplekse:"),
    ("Polistibrick za ansambluri rezidențiale:", "Polistibrick za stambene komplekse:"),
    ("primă la revânzare", "premija pri preprodaji"),
    ("datorită standardului pasiv", "zbog pasivnog standarda"),
    ("datorită stiardului pasiv", "zbog pasivnog standarda"),
    ("de 3× mai rapidă", "3× brža"),
    ("de 3× više rapidă", "3× brža"),
    ("(mai puține dobânzi)", "(manje kamata)"),
    ("(više puține dobânzi)", "(manje kamata)"),
    ("tarife de volum", "volumske cijene"),
    ("acord-cadru dedicat", "posvećeni okvirni ugovor"),
    ("acord-cadru dedicat pentru programe 25+", "posvećeni okvirni ugovor za programe 25+"),
    ("Calculează rentabilitatea", "Izračunajte profitabilnost"),
    ("Vezi tarifele de volum", "Pogledajte volumske cijene"),
    ("Cele 4 griji reale", "4 stvarne brige"),
    ("Cele 4 îngrijorări reale", "4 stvarne brige"),
    ("Ce vă <em style=\"font-style:italic;color:var(--red);font-weight:400;\">amenință marja.</em>",
     "Šta vam <em style=\"font-style:italic;color:var(--red);font-weight:400;\">ugrožava maržu.</em>"),
    ("Polistibrick a fost conceput pentru a rezolva cele 4 riscuri majore ale oricărui program rezidențial sau de închiriere.",
     "Polistibrick je osmišljen da riješi 4 glavna rizika svakog stambenog ili najmodavnog programa."),
    ("« Întârzierile de șantier mă costă dobânzi. »", "« Kašnjenja na gradilištu me koštaju kamata. »"),
    ("« Întârzierile de gradilište mă costă dobânzi. »", "« Kašnjenja na gradilištu me koštaju kamata. »"),
    ("Structura Polistibrick:", "Polistibrick struktura:"),
    ("(față de 4–5 luni cu cărămida)", "(naspram 4–5 mjeseci sa ciglom)"),
    ("(față de 4–5 mjeseci sa cărămida)", "(naspram 4–5 mjeseci sa ciglom)"),
    ("Pe un ansamblu de 10 case", "Na kompleksu od 10 kuća"),
    ("Pe un kompleks de 10 kuće", "Na kompleksu od 10 kuća"),
    ("câștigați", "dobijate"),
    ("pe lot", "po parceli"),
    ("mai puține dobânzi", "manje kamata"),
    ("više puține dobânzi", "manje kamata"),
    ("monetizare mai rapidă", "brža monetizacija"),
    ("monetizare više rapidă", "brža monetizacija"),
    ("« Depășirile de cost erodează marja. »", "« Prekoračenja troškova smanjuju maržu. »"),
    ("« Depășirile de trošak erodează marja. »", "« Prekoračenja troškova smanjuju maržu. »"),
    ("Prețuri panouri", "Cijene panela"),
    ("Cijena panouri", "Cijene panela"),
    ("fixate contractual", "ugovoreno fiksno"),
    ("fixat contractual", "ugovoreno fiksno"),
    ("Calculat de Polistibrick = fără surprize la cantități.",
     "Polistibrick kalkulacija = bez iznenađenja u količinama."),
    ("Calculat de Polistibrick = bez surprize la cantități.",
     "Polistibrick kalkulacija = bez iznenađenja u količinama."),
    ("Termene livrare", "Rokovi isporuke"),
    ("garantate", "garantovani"),
    ("garantate în acord-cadru", "garantovani okvirnim ugovorom"),
    ("« Cum maximizez valoarea la revânzare / închiriere? »",
     "« Kako maksimizovati vrijednost pri preprodaji / najmu? »"),
    ("« Kako maximizez valoarea la revânzare / închiriere? »",
     "« Kako maksimizovati vrijednost pri preprodaji / najmu? »"),
    ("« Kako valorific la revânzare / închiriere? »",
     "« Kako maksimizovati vrijednost pri preprodaji / najmu? »"),
    ("Casă pasivă certificată", "Certificirana pasivna kuća"),
    ("Kuća pasivă certificată", "Certificirana pasivna kuća"),
    ("Kuća pasivă certificirana", "Certificirana pasivna kuća"),
    ("se vinde cu", "prodaje se sa"),
    ("se vinde sa", "prodaje se sa"),
    ("pe piață", "na tržištu"),
    ("pje piață", "na tržištu"),
    ("La închiriere", "Pri najmu"),
    ("vacanță mai mică", "manja praznina"),
    ("vacanță više mică", "manja praznina"),
    ("cheltuieli", "troškovi"),
    ("atrac chiriasi premium", "privlače premium stanare"),
    ("atrac chiriai premium", "privlače premium stanare"),
    ("« Dacă RE2030 apare în 5 ani și obligă renovări? »",
     "« Ako RE2030 dođe za 5 godina i zahtijeva renoviranje? »"),
    ("« Dacă RE2030 apare în 5 godina i obligă renovări? »",
     "« Ako RE2030 dođe za 5 godina i zahtijeva renoviranje? »"),
    ("deja depășesc cu mult RE2020", "već daleko nadmašuju RE2020"),
    ("deja depășesc cu mult RE2020 i anticipează cerințele viitoare",
     "već daleko nadmašuju RE2020 i anticipiraju buduće zahtjeve"),
    ("deja depășesc cu mult RE2020 i anticipează cerințele viitoare.",
     "već daleko nadmašuju RE2020 i anticipiraju buduće zahtjeve."),
    ("Ansamblul rămâne conform 30+ ani", "Kompleks ostaje usklađen 30+ godina"),
    ("Kompleksul rămâne conform 30+ ani", "Kompleks ostaje usklađen 30+ godina"),
    ("fără costuri ascunse de renovare", "bez skrivenih troškova renoviranja"),
    ("bez costuri ascunse de renovare", "bez skrivenih troškova renoviranja"),
    ("3 pârghii pentru programul tău", "3 poluge za vaš program"),
    ("3 pârghii za programul vas", "3 poluge za vaš program"),
    ("Ce schimbă", "Šta mijenja"),
    ("Ce schimbă <em style=\"font-style:italic;color:var(--red);font-weight:400;\">profitabilitatea ta.</em>",
     "Šta mijenja <em style=\"font-style:italic;color:var(--red);font-weight:400;\">vašu profitabilnost.</em>"),
    ("profitabilitatea ta", "vašu profitabilnost"),
    ("profitabilitatea vas", "vašu profitabilnost"),
    ("profitabilitatea voastră", "vašu profitabilnost"),
    ("la revânzare", "pri preprodaji"),
    ("O casă pasivă certificată se vinde sistematic peste prețul pieței.",
     "Certificirana pasivna kuća sistematski se prodaje iznad tržišne cijene."),
    ("Kuća pasivă certificată se vinde sistematic peste prețul pieței.",
     "Certificirana pasivna kuća sistematski se prodaje iznad tržišne cijene."),
    ("Pentru un ansamblu de 10 case la €400.000", "Za kompleks od 10 kuća po €400.000"),
    ("Za un kompleks de 10 kuće la €400.000", "Za kompleks od 10 kuća po €400.000"),
    ("aceasta reprezintă", "to predstavlja"),
    ("marjă brută suplimentară", "dodatnu bruto maržu"),
    ("de timeline", "rokova"),
    ("Structură în 4–6 săptămâni", "Struktura za 4–6 sedmica"),
    ("Structura în 4–6 sedmice", "Struktura za 4–6 sedmica"),
    ("(vs 4–5 luni)", "(naspram 4–5 mjeseci)"),
    ("(vs 4–5 mjeseci)", "(naspram 4–5 mjeseci)"),
    ("Pe un program de 10 unități", "Na programu od 10 jedinica"),
    ("Pe un program de 10 unități, câștigați 3–4 luni",
     "Na programu od 10 jedinica dobijate 3–4 mjeseca"),
    ("dobândă credit redusă", "smanjene kamate na kredit"),
    ("dobândă credit redusă + monetizare accelerată a capitalului investit.",
     "smanjene kamate na kredit + ubrzana monetizacija uloženog kapitala."),
    ("Tarife <em>ansamblu</em>", "Cijene <em>kompleksa</em>"),
    ("Tarife <em>ensemble</em>", "Cijene <em>kompleksa</em>"),
    ("Remise volume de la 5 unități", "Volumski popusti od 5 jedinica"),
    ("Remise volume de la 5 unități.", "Volumski popusti od 5 jedinica."),
    ("−15% și acord-cadru dedicat", "−15% i posvećeni okvirni ugovor"),
    ("−15% i acord-cadru dedicat", "−15% i posvećeni okvirni ugovor"),
    ("pentru 25+ unități", "za 25+ jedinica"),
    ("za 25+ unități", "za 25+ jedinica"),
    ("Project manager Polistibrick alocat pe durata programului.",
     "Polistibrick project manager dodijeljen za trajanje programa."),
    ("Co-marketing pe canalele noastre", "Ko-marketing na našim kanalima"),
    ("Co-marketing sur nos canaux", "Ko-marketing na našim kanalima"),
    ("Simulare rentabilitate", "Simulacija profitabilnosti"),
    ("Cât câștigă în plus ansamblul tău", "Koliko dodatno zarađuje vaš kompleks"),
    ("Cât câștigă în plus kompleksul vas", "Koliko dodatno zarađuje vaš kompleks"),
    ("Introduceți numărul de unități din ansamblu.",
     "Unesite broj jedinica u kompleksu."),
    ("Introduceți numărul de unități din kompleks.",
     "Unesite broj jedinica u kompleksu."),
    ("Calculăm câștigul estimat la revânzare, timpul câștigat și dobânzile evitate.",
     "Računamo procijenjeni dobitak pri preprodaji, ušteđeno vrijeme i izbjegnute kamate."),
    ("Calculăm câștigul estimat la revânzare, timpul câștigat i dobânzile evitate.",
     "Računamo procijenjeni dobitak pri preprodaji, ušteđeno vrijeme i izbjegnute kamate."),
    ("Număr de unități în ansamblul tău:", "Broj jedinica u vašem kompleksu:"),
    ("Număr de unități în kompleksul vas:", "Broj jedinica u vašem kompleksu:"),
    ("unități", "jedinica"),
    ("Primă la revânzare", "Premija pri preprodaji"),
    ("Prim la revânzare", "Premija pri preprodaji"),
    ("vs construcție clasică", "naspram klasične gradnje"),
    ("vs construcție clasică (+18%)", "naspram klasične gradnje (+18%)"),
    ("Timp câștigat", "Ušteđeno vrijeme"),
    ("Timp câștigat", "Ušteđeno vrijeme"),
    ("Dobânzi evitate", "Izbjegnute kamate"),
    ("cu credit la 4,5%", "sa kreditom od 4,5%"),
    ("Pe un ansamblu de", "Na kompleksu od"),
    ("Pe un kompleks de", "Na kompleksu od"),
    ("câștigul total estimat", "procijenjeni ukupni dobitak"),
    ("câștigul total estimat cu Polistibrick", "procijenjeni ukupni dobitak sa Polistibrick-om"),
    ("vs o construcție clasică", "naspram klasične gradnje"),
    ("vs o construcție clasică.", "naspram klasične gradnje."),
    ("Estimare bazată pe ipoteze standard:", "Procjena na osnovu standardnih pretpostavki:"),
    ("Estimare bazată pe ipoteze stiard:", "Procjena na osnovu standardnih pretpostavki:"),
    ("preț mediu de vânzare", "prosječna prodajna cijena"),
    ("primă pasivă", "pasivna premija"),
    ("credit la 4,5%", "kredit od 4,5%"),
    ("Pentru un calcul precis pe proiectul tău, contactați-ne pentru un studiu personalizat.",
     "Za precizan proračun vašeg projekta, kontaktirajte nas za personalizovanu studiju."),
    ("Za un calcul precis pe projekatul vas, contactați-ne za o studiu personalizată.",
     "Za precizan proračun vašeg projekta, kontaktirajte nas za personalizovanu studiju."),
    ("Niveluri parteneriat", "Nivoi partnerstva"),
    ("3 niveluri de parteneriat în funcție de dimensiunea programului.",
     "3 nivoa partnerstva u zavisnosti od veličine programa."),
    ("Mai mult suport, tarife mai bune, acord-cadru dedicat.",
     "Više podrške, bolje cijene, posvećeni okvirni ugovor."),
    ("Devino partener dezvoltator", "Postanite partnerski developer"),
    ("Postanite investitor partner", "Postanite partnerski investitor"),
    ("Postanite dezvoltator partner", "Postanite partnerski developer"),
    ("Program de 5 unități", "Program od 5 jedinica"),
    ("Program de 10 unități", "Program od 10 jedinica"),
    ("Program de 25+ unități", "Program od 25+ jedinica"),
    ("Proces dezvoltator", "Proces developera"),
    ("Ansambluri finalizate", "Završeni kompleksi"),
    ("Studii de caz", "Studije slučaja"),
    ("Programe rezidențiale", "Stambeni programi"),
    ("Construim astăzi <em>casele de mâine.</em>", "Gradimo danas <em>kuće sutrašnjice.</em>"),
    ("Construim astăzi <em>kuće de mâine.</em>", "Gradimo danas <em>kuće sutrašnjice.</em>"),
    ("Kuća tradițională a fost concepută acum 200 de ani.",
     "Tradicionalna kuća je osmišljena prije 200 godina."),
    ("Kuća tradițională a fost concepută acum 200 de godina.",
     "Tradicionalna kuća je osmišljena prije 200 godina."),
    ("Funcționează pe baza facturilor:", "Funkcioniše na osnovu računa:"),
    ("Funcționează pe baza računilor:", "Funkcioniše na osnovu računa:"),
    ("gaz, lemne, curent electric, aer condiționat",
     "gas, drva, struja, klimatizacija"),
    ("o întreținere costisitoare și nesfârșită",
     "skupo i beskrajno održavanje"),
    ("o întreținere costisitoare i nesfârșită",
     "skupo i beskrajno održavanje"),
    ("Această casă nu mai este o investiție; este o obligație.",
     "Ova kuća više nije investicija; to je obaveza."),
    ("Ova kuća nu više je o investiție; je o obligație.",
     "Ova kuća više nije investicija; to je obaveza."),
    ("O casă întreagă în 1 lună față de 4–5 luni cu sistem clasic.",
     "Cijela kuća za 1 mjesec naspram 4–5 mjeseci sa klasičnim sistemom."),
    ("O kuća întreagă în 1 mjesec față de 4–5 mjeseci sa sistem clasic.",
     "Cijela kuća za 1 mjesec naspram 4–5 mjeseci sa klasičnim sistemom."),
    ("Mai puține echipe, mai puține materiale, mai puține întârzieri.",
     "Manje timova, manje materijala, manje kašnjenja."),
    ("Više puține echipe, više puține materiale, više puține întârzieri.",
     "Manje timova, manje materijala, manje kašnjenja."),
    ("Mai puțin stres pentru proprietar.", "Manje stresa za vlasnika."),
    ("Više puțin stres za vlasnik.", "Manje stresa za vlasnika."),
    ("Reducerea consumului de energie cu 70 %", "Smanjenje potrošnje energije za 70%"),
    ("Reducerea consumului de energija sa 70 %", "Smanjenje potrošnje energije za 70%"),
    ("înseamnă mai puține emisii pe durata de viață a casei.",
     "znači manje emisija tokom vijeka trajanja kuće."),
    ("înseamnă više puține emisii pe durata de viață a kuće.",
     "znači manje emisija tokom vijeka trajanja kuće."),
    ("Construim case care nu mai poluează odată locuite.",
     "Gradimo kuće koje više ne zagađuju nakon useljenja."),
    ("Construim kuće koji nu više poluează odată locuite.",
     "Gradimo kuće koje više ne zagađuju nakon useljenja."),
    ("Construiește cu noi", "Gradite sa nama"),
    ("Construiește sa mi", "Gradite sa nama"),
    ("Découvrez nos études de cas", "Otkrijte naše studije slučaja"),
    ("Découvrir le projet →", "Otkrijte projekat →"),
    ("Villa d'Architecte · Espagne", "Arhitektonska vila · Španija"),
    ("Maison de montagne · Roumanie", "Planinska kuća · Rumunija"),
    ("Ensemble collectif · France", "Stambeni kompleks · Francuska"),
    ("Demander le dossier technique →", "Zatražite tehnički dossier →"),
    ("Cette photo de chantier est issue du dossier technique confidentiel. Contactez notre équipe pour y accéder.",
     "Ova fotografija gradilišta dolazi iz povjerljivog tehničkog dossiera. Kontaktirajte naš tim za pristup."),
    ("Această fotografie de șantier provine din dosarul tehnic confidențial. Kontaktați echipa noastră pentru acces.",
     "Ova fotografija gradilišta dolazi iz povjerljivog tehničkog dossiera. Kontaktirajte naš tim za pristup."),
    ("Choisir le pays", "Odaberite zemlju"),
    ("Choisir le zemlja", "Odaberite zemlju"),
    ("Kuća de arhitect contemporană cu console, realizată cu Polistibrick",
     "Savremena arhitektonska kuća sa konzolama, izgrađena sa Polistibrick-om"),
    ("Kuća de arhitect contemporană sa console, realizată sa Polistibrick",
     "Savremena arhitektonska kuća sa konzolama, izgrađena sa Polistibrick-om"),
    ("Cuplu pe terasa unei case Polistibrick la apus",
     "Par na terasi Polistibrick kuće pri zalasku sunca"),
    ("Cuplu pe terasa unei kuće Polistibrick la apus",
     "Par na terasi Polistibrick kuće pri zalasku sunca"),
    ("De la contemporan la tradițional, de la P la P+3, în zone reci sau mediteraneene",
     "Od savremenog do tradicionalnog, od P do P+3, u hladnim ili mediteranskim zonama"),
    ("De la contemporan la tradițional, de la P la P+3, în zone reci ili mediteraneene",
     "Od savremenog do tradicionalnog, od P do P+3, u hladnim ili mediteranskim zonama"),
    ("Polistibrick se adaptează oricărei arhitecturi.", "Polistibrick se prilagođava svakoj arhitekturi."),
    ("Polistibrick se adaptează oricărei arhitecturi",
     "Polistibrick se prilagođava svakoj arhitekturi"),
    ("Zašto une pasivna kuća doit-elle être hermétique ?",
     "Zašto pasivna kuća mora biti hermetična?"),
    ("How does the Blower Door test work and why does Polistibrick pass it without any additions.",
     "Kako funkcioniše Blower Door test i zašto Polistibrick prolazi bez dodataka."),
    ("How does the Blower Door test work i why does Polistibrick pass it without any additions.",
     "Kako funkcioniše Blower Door test i zašto Polistibrick prolazi bez dodataka."),
    ("prime à la revente pour passive", "premija pri preprodaji pasivne kuće"),
    ("Intérêts économisés", "Ušteđene kamate"),
    ("Demie de documentation", "Zahtjev za dokumentaciju"),
    ("Demie de devis", "Zahtjev za ponudu"),
    ("Demande+de+dossier+technique", "Zahtjev+za+tehnički+dossier"),
    ("Demie+d+un+dossier+technique+complet", "Zahtjev+za+kompletan+tehnički+dossier"),
    ("Demie+documentation+technique", "Zahtjev+dokumentacije"),
    ("Demie+de+document+brevet+Polistibrick", "Zahtjev+dokumenta+patenta+Polistibrick"),
    ("Document+complet+du+brevet+Polistibrick", "Kompletan+dokument+patenta+Polistibrick"),
    ("Dossier+Technique+Complet", "Kompletan+tehnički+dossier"),
    ("Dokumentacija+investisseurs", "Dokumentacija+investitora"),
    ("Documentatie+investitori", "Dokumentacija+investitora"),
    ("../../kontakt/", "../../contact/"),
    ("Cerere+documentatie+investitori", "Zahtjev+dokumentacija+investitori"),
    ("Cerere+ponuda", "Zahtjev+ponuda"),
    ("Investitor / Investitor", "Investitor / Developer"),
    ("dezvoltator / investitor", "developer / investitor"),
    ("dezvoltator", "developer"),
    ("Dezvoltator", "Developer"),
    ("dezvoltatori", "developere"),
    ("Dezvoltatori", "Developere"),
    ("Ansambluri rezidențiale pasive", "Pasivni stambeni kompleksi"),
    ("ansambluri rezidențiale", "stambeni kompleksi"),
    ("ansamblu", "kompleks"),
    ("Ansamblu", "Kompleks"),
    ("ansambluri", "kompleksi"),
    ("Ansambluri", "Kompleksi"),
]

# Additional word-boundary pairs
WORDS = [
    ("construcție", "gradnja"), ("Construcție", "Gradnja"), ("construcții", "gradnje"),
    ("construcția", "gradnja"), ("construcției", "gradnje"),
    ("structură", "struktura"), ("Structură", "Struktura"), ("structura", "struktura"),
    ("clasică", "klasična"), ("Clasică", "Klasična"), ("clasic", "klasični"),
    ("clasică", "klasična"), ("tradițională", "tradicionalna"), ("Tradițională", "Tradicionalna"),
    ("tradițional", "tradicionalni"), ("Tradițional", "Tradicionalni"),
    ("personalizată", "personalizovana"), ("personalizat", "personalizovan"),
    ("personalizată", "personalizovana"), ("personalizat", "personalizovan"),
    ("personalizată", "personalizovana"),
    ("echipă", "tim"), ("Echipă", "Tim"), ("echipe", "timovi"), ("Echipe", "Timovi"),
    ("echipele", "timove"), ("echipa", "tim"),
    ("unități", "jedinica"), ("Unități", "Jedinica"), ("unitate", "jedinica"),
    ("unitatea", "jedinica"), ("unităților", "jedinica"),
    ("producție", "proizvodnja"), ("Producție", "Proizvodnja"),
    ("punți", "mostovi"), ("Punți", "Mostovi"), ("punte", "most"),
    ("funcție", "funkcija"), ("Funcție", "Funkcija"), ("funcția", "funkcija"),
    ("tâmplărie", "stolarija"), ("Tâmplărie", "Stolarija"),
    ("condiționat", "klimatizacija"), ("Condiționat", "Klimatizacija"),
    ("comandă", "narudžba"), ("Comandă", "Narudžba"),
    ("integrată", "integrisana"), ("integrat", "integrisan"),
    ("instalații", "instalacije"), ("Instalații", "Instalacije"),
    ("documentația", "dokumentacija"), ("Documentația", "Dokumentacija"),
    ("bibliotecă", "biblioteka"), ("Bibliotecă", "Biblioteka"),
    ("revânzare", "preprodaja"), ("Revânzare", "Preprodaja"),
    ("primești", "dobijate"), ("Primești", "Dobijate"),
    ("continuă", "nastavlja"), ("Continuă", "Nastavlja"),
    ("bucătărie", "kuhinja"), ("Bucătărie", "Kuhinja"),
    ("niciodată", "nikada"), ("Niciodată", "Nikada"),
    ("placă", "ploča"), ("Placă", "Ploča"),
    ("acustică", "akustika"), ("Acustică", "Akustika"),
    ("fișa", "list"), ("Fișa", "List"),
    ("suplimentară", "dodatna"), ("Suplimentară", "Dodatna"),
    ("armătură", "armatura"), ("Armătură", "Armatura"),
    ("funcționează", "funkcioniše"), ("Funcționează", "Funkcioniše"),
    ("rapidă", "brza"), ("Rapidă", "Brza"), ("rapid", "brz"),
    ("spațiu", "prostor"), ("Spațiu", "Prostor"),
    ("tencuială", "fasada"), ("Tencuială", "Fasada"),
    ("piscină", "bazen"), ("Piscină", "Bazen"),
    ("montați", "montirajte"), ("Montați", "Montirajte"),
    ("solicită", "zatražite"), ("Solicită", "Zatražite"),
    ("totală", "ukupna"), ("Totală", "Ukupna"),
    ("reală", "stvarna"), ("Reală", "Stvarna"),
    ("pasivă", "pasivna"), ("Pasivă", "Pasivna"),
    ("cărămida", "cigla"), ("Cărămida", "Cigla"),
    ("puțin", "malo"), ("Puțin", "Malo"), ("puține", "malo"), ("Puține", "Malo"),
    ("curând", "uskoro"), ("Curând", "Uskoro"),
    ("decât", "nego"), ("Decât", "Nego"),
    ("dacă", "ako"), ("Dacă", "Ako"),
    ("cât", "koliko"), ("Cât", "Koliko"),
    ("către", "prema"), ("Către", "Prema"),
    ("că", "da"), ("Că", "Da"),
    ("până", "do"), ("Până", "Do"),
    ("singură", "jedna"), ("Singură", "Jedna"),
    ("între", "između"), ("Între", "Između"),
    ("față", "naspram"), ("Față", "Naspram"),
    ("după", "nakon"), ("După", "Nakon"),
    ("viață", "život"), ("Viață", "Život"),
    ("vă", "vas"), ("Vă", "Vas"),
    ("tău", "vaš"), ("Tău", "Vaš"), ("tăi", "vaši"), ("ta", "vaša"),
    ("îl", "ga"), ("Îl", "Ga"),
    ("să", "da"),
    ("în", "u"), ("În", "U"),
    ("Maximizați", "Maksimizujte"), ("maximizați", "maksimizujte"),
    ("Minimizați", "Minimizujte"), ("minimizați", "minimizujte"),
    ("primă", "premija"), ("Primă", "Premija"),
    ("riscul", "rizik"), ("Riscul", "Rizik"),
    ("marja", "marža"), ("Marja", "Marža"),
    ("marjei", "marže"),
    ("dobânzi", "kamate"), ("Dobânzi", "Kamate"), ("dobândă", "kamata"),
    ("monetizare", "monetizacija"), ("Monetizare", "Monetizacija"),
    ("programului", "programa"), ("programul", "program"),
    ("program", "program"), ("Program", "Program"),
    ("programe", "programe"), ("Programe", "Programe"),
    ("programele", "programe"),
    ("dezvoltator", "developer"), ("Dezvoltator", "Developer"),
    ("dezvoltatori", "developere"), ("Dezvoltatori", "Developere"),
    ("dezvoltatorul", "developera"),
    ("promoteur", "developer"),
    ("proprietar", "vlasnik"), ("Proprietar", "Vlasnik"),
    ("proprietarul", "vlasnika"), ("proprietarilor", "vlasnika"),
    ("proprietarului", "vlasnika"),
    ("particulier", "pojedinac"),
    ("architecte", "arhitekt"), ("constructeur", "građevinac"),
    ("architecte-bet", "arhitekt-bet"),
    ("arhitect-bet", "arhitekt-bet"),
    ("constructor", "građevinac"),
    ("proiectul", "projekat"), ("proiectului", "projekta"),
    ("proiectelor", "projekata"),
    ("șantier", "gradilište"), ("Șantier", "Gradilište"),
    ("șantierul", "gradilište"),
    ("locuințe", "stanovi"), ("Locuințe", "Stanovi"),
    ("locuință", "stan"), ("Locuință", "Stan"),
    ("locuințelor", "stanova"),
    ("locuiește", "živi"), ("Locuiește", "Živi"),
    ("proprietarului", "vlasnika"),
    ("Numele proprietarului", "Ime vlasnika"),
    ("[Numele proprietarului]", "[Ime vlasnika]"),
    ("Vlasnik · Locuiește din", "Vlasnik · Živi od"),
    ("Locuiește din više", "Živi od"),
    ("clădire", "zgrada"), ("Clădire", "Zgrada"),
    ("clădiri", "zgrade"), ("Clădiri", "Zgrade"),
    ("clădirii", "zgrade"),
    ("consumului", "potrošnje"), ("consumul", "potrošnja"),
    ("emisii", "emisija"), ("Emisii", "Emisija"),
    ("poluează", "zagađuje"), ("Poluează", "Zagađuje"),
    ("locuite", "useljene"), ("Locuite", "Useljene"),
    ("odată", "jednom"), ("Odată", "Jednom"),
    ("întreținere", "održavanje"), ("Întreținere", "Održavanje"),
    ("obligație", "obaveza"), ("Obligație", "Obaveza"),
    ("investiție", "investicija"), ("Investiție", "Investicija"),
    ("concepută", "osmišljena"), ("Concepută", "Osmišljena"),
    ("conceput", "osmišljen"), ("Conceput", "Osmišljen"),
    ("mâine", "sutrašnjice"), ("Mâine", "Sutrašnjice"),
    ("casele", "kuće"), ("Casele", "Kuće"),
    ("stres", "stres"), ("Stres", "Stres"),
    ("proprietar", "vlasnik"),
    ("materiale", "materijali"), ("Materiale", "Materijali"),
    ("întârzieri", "kašnjenja"), ("Întârzieri", "Kašnjenja"),
    ("întârziere", "kašnjenje"), ("Întârziere", "Kašnjenje"),
    ("reducerea", "smanjenje"), ("Reducerea", "Smanjenje"),
    ("reducere", "smanjenje"), ("Reducere", "Smanjenje"),
    ("durata", "trajanje"), ("Durata", "Trajanje"),
    ("vieții", "trajanja"), ("vieții", "trajanja"),
    ("casei", "kuće"), ("Casei", "Kuće"),
    ("gradnja", "gradnja"),
    ("construim", "gradimo"), ("Construim", "Gradimo"),
    ("construiește", "gradite"), ("Construiește", "Gradite"),
    ("construiți", "gradite"), ("Construiți", "Gradite"),
    ("construită", "izgrađena"), ("Construită", "Izgrađena"),
    ("construite", "izgrađene"), ("Construite", "Izgrađene"),
    ("construit", "izgrađeno"), ("Construit", "Izgrađeno"),
    ("finalizată", "završena"), ("Finalizată", "Završena"),
    ("finalizat", "završen"), ("Finalizat", "Završen"),
    ("finalizate", "završene"), ("Finalizate", "Završene"),
    ("livrată", "isporučena"), ("Livrată", "Isporučena"),
    ("livrat", "isporučen"), ("Livrat", "Isporučen"),
    ("livrate", "isporučene"), ("Livrate", "Isporučene"),
    ("cheie", "ključ"), ("Cheie", "Ključ"),
    ("luni", "mjeseci"), ("Luni", "Mjeseci"), ("lună", "mjesec"), ("Lună", "Mjesec"),
    ("săptămâni", "sedmice"), ("Săptămâni", "Sedmice"),
    ("săptămână", "sedmica"), ("Săptămâna", "Sedmica"),
    ("săpt", "sedm"),
    ("persoane", "osobe"), ("Persoane", "Osobe"), ("persoană", "osoba"),
    ("montat", "montiran"), ("Montat", "Montiran"),
    ("monta", "montira"), ("Monta", "Montira"),
    ("montează", "montira"), ("Montează", "Montira"),
    ("montarea", "montaža"), ("Montarea", "Montaža"),
    ("manipulează", "manipulišu"), ("Manipulează", "Manipulišu"),
    ("asamblează", "sastavljaju"), ("Asamblează", "Sastavljaju"),
    ("precizie", "preciznost"), ("Precizie", "Preciznost"),
    ("milimetrică", "milimetarska"), ("Milimetrică", "Milimetarska"),
    ("încălzire", "grijanje"), ("Încălzire", "Grijanje"),
    ("cheltuieli", "troškovi"), ("Cheltuieli", "Troškovi"),
    ("familiei", "porodice"), ("Familiei", "Porodice"),
    ("vecinătatea", "susjede"), ("Vecinătatea", "Susjede"),
    ("uimit", "iznenadila"), ("Uimit", "Iznenadila"),
    ("climat", "klima"), ("Climat", "Klima"),
    ("continental", "kontinentalna"), ("Continental", "Kontinentalna"),
    ("iernile", "zime"), ("Iernile", "Zime"),
    ("coborî", "padnu"), ("Coborî", "Padnu"),
    ("performanța", "performansa"), ("Performanța", "Performansa"),
    ("continuă", "kontinuirana"), ("Continuă", "Kontinuirana"),
    ("elimină", "eliminira"), ("Elimină", "Eliminira"),
    ("abuzive", "visoke"), ("Abuzive", "Visoke"),
    ("longevitate", "dugovječnost"), ("Longevitate", "Dugovječnost"),
    ("placarea", "obloga"), ("Placarea", "Obloga"),
    ("fibre-ciment", "fiber-cement"),
    ("reacție", "reakcija"), ("Reacție", "Reakcija"),
    ("necombustibilă", "negoriva"), ("Necombustibilă", "Negoriva"),
    ("program imobiliar", "stambeni program"),
    ("Program imobiliar", "Stambeni program"),
    ("anvergură", "veličina"), ("Anvergură", "Veličina"),
    ("trebuia", "trebalo"), ("Trebuia", "Trebalo"),
    ("livrez", "isporučim"), ("Livrez", "Isporučim"),
    ("certificate", "certificirane"), ("Certificate", "Certificirane"),
    ("termene", "rokovi"), ("Termene", "Rokovi"),
    ("stricte", "strogi"), ("Stricte", "Strogi"),
    ("permis", "omogućio"), ("Permis", "Omogućio"),
    ("finalizăm", "završavamo"), ("Finalizăm", "Završavamo"),
    ("câștigând", "dobijajući"), ("Câștigând", "Dobijajući"),
    ("planificare", "planiranje"), ("Planificare", "Planiranje"),
    ("față de", "naspram"), ("Față de", "Naspram"),
    ("cărămidă", "cigla"), ("Cărămidă", "Cigla"),
    ("tradițională", "tradicionalna"),
    ("predictibilitatea", "predvidivost"), ("Predictibilitatea", "Predvidivost"),
    ("sistemului", "sistema"),
    ("atu", "prednost"), ("Atu", "Prednost"),
    ("financiar", "finansijska"), ("Financiar", "Finansijska"),
    ("incontestabil", "nepobitna"), ("Incontestabil", "Nepobitna"),
    ("ansamblu", "kompleks"), ("Ansamblu", "Kompleks"),
    ("ansambluri", "kompleksi"), ("Ansambluri", "Kompleksi"),
    ("rezidențial", "stambeni"), ("Rezidențial", "Stambeni"),
    ("rezidențiale", "stambene"), ("Rezidențiale", "Stambene"),
    ("colectiv", "kolektivni"), ("Colectiv", "Kolektivni"),
    ("demonstră", "pokazuje"), ("Demonstră", "Pokazuje"),
    ("aplicabilitatea", "primjenjivost"), ("Aplicabilitatea", "Primjenjivost"),
    ("industrială", "industrijska"), ("Industrială", "Industrijska"),
    ("coulées", "betonirane"),
    ("tranches", "serije"),
    ("successives", "uzastopne"),
    ("obținut", "dobio"), ("Obținut", "Dobio"),
    ("certification", "certifikacija"),
    ("directement", "direktno"),
    ("premier", "prvi"),
    ("coup", "put"),
    ("garantissant", "garantujući"),
    ("retour", "povrat"),
    ("investissement", "investicija"),
    ("optimal", "optimalan"),
    ("prime", "premija"),
    ("vente", "prodaja"),
    ("Terrassement", "Iskop"),
    ("Préparation", "Priprema"),
    ("plate-forme", "platforme"),
    ("dalles", "ploče"),
    ("Élévation", "Podizanje"),
    ("Montage", "Montaža"),
    ("parallèle", "paralelno"),
    ("coffrantes", "oplata"),
    ("Pose", "Postavljanje"),
    ("simultanée", "istovremeno"),
    ("thermiques", "termičke"),
    ("grue", "dizalica"),
    ("Coulage", "Betoniranje"),
    ("masse", "masovno"),
    ("Gestion", "Upravljanje"),
    ("logistique", "logistika"),
    ("phases", "fazama"),
    ("Installations", "Instalacije"),
    ("techniques", "tehničke"),
    ("Passage", "Prolaz"),
    ("direct", "direktan"),
    ("gaines", "kanala"),
    ("Finalisé", "Završeno"),
    ("logements", "stanova"),
    ("certifiés", "certificirani"),
    ("vendus", "prodati"),
]

def wb_replace(text: str, old: str, new: str) -> str:
    if len(old) >= 8 or " " in old or "—" in old or "·" in old or "<" in old:
        return text.replace(old, new)
    return re.sub(
        r"(?<![\wăâîșțĂÂÎȘȚ])" + re.escape(old) + r"(?![\wăâîșțĂÂÎȘȚ])",
        new, text
    )


def translate_block(text: str) -> str:
    for old, new in sorted(PHRASES, key=lambda x: -len(x[0])):
        text = text.replace(old, new)
    for old, new in sorted(WORDS, key=lambda x: -len(x[0])):
        text = wb_replace(text, old, new)
    return text


def process(text: str) -> str:
    parts = re.split(r"(<script[\s\S]*?</script>|<style[\s\S]*?</style>)", text, flags=re.I)
    return "".join(p if i % 2 else translate_block(p) for i, p in enumerate(parts))


def main():
    changed = 0
    for html in sorted(ROOT.rglob("*.html")):
        t = html.read_text(encoding="utf-8")
        n = process(t)
        if n != t:
            html.write_text(n, encoding="utf-8")
            changed += 1
    print(f"Pass4: updated {changed} files ({len(PHRASES)} phrases, {len(WORDS)} words)")


if __name__ == "__main__":
    main()
