#!/usr/bin/env python3
"""Second pass: RO→CNR via word-boundary replacements (safe for HTML)."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent / "countries/me"

# Longest-first whole-word RO→CNR (ijekavian)
WORD_PAIRS = [
    ("Pentru proprietari · Casa pe viață, fără facturi — Polistibrick", "Za vlasnike · Kuća za cijeli život bez računa — Polistibrick"),
    ("Construiți o casă pasivă certificată, fără facturi mari la energie, garanție 50 de ani. Calculator de economii, comparație transparentă, arhitecți certificați Polistibrick în apropiere.", "Gradite certificiranu pasivnu kuću, bez visokih računa za energiju, garancija 50 godina. Kalkulator ušteda, transparentno poređenje, certificirani arhitekti Polistibrick u vašoj blizini."),
    ("Sistem ICF complet — pereți, planșee, acoperiș. Standard A+++. Construit în 4 săptămâni. Fără compromis, fără facturi.", "Kompletan ICF sistem — zidovi, podovi, krov. standard A+++. Izgrađeno za 4 sedmice. Bez kompromisa, bez računa."),
    ("Detectăm că ești în", "Detektujemo da ste u"),
    ("Vizitezi", "Posjećujete"),
    ("Da, mergi", "Da, idi"),
    ("Rămân aici", "Ostajem ovdje"),
    ("Schimbă țara", "Promijeni zemlju"),
    ("casă pasivă", "pasivna kuća"),
    ("Casă pasivă", "Pasivna kuća"),
    ("Casa Pasivă", "Pasivna kuća"),
    ("case pasive", "pasivne kuće"),
    ("case pasivă", "pasivne kuće"),
    ("construiți", "gradite"),
    ("Construiți", "Gradite"),
    ("construită", "izgrađena"),
    ("construite", "izgrađene"),
    ("construit", "izgrađeno"),
    ("Construit", "Izgrađeno"),
    ("construirea", "gradnja"),
    ("Construirea", "Gradnja"),
    ("construire", "gradnja"),
    ("construim", "gradimo"),
    ("construiește", "gradi"),
    ("construiesc", "grade"),
    ("construită", "izgrađena"),
    ("proprietari", "vlasnici"),
    ("Proprietari", "Vlasnici"),
    ("proprietar", "vlasnik"),
    ("Proprietar", "Vlasnik"),
    ("proprietarul", "vlasnik"),
    ("proprietarilor", "vlasnika"),
    ("constructori", "građevinci"),
    ("Constructori", "Građevinci"),
    ("constructor", "građevinac"),
    ("Constructor", "Građevinac"),
    ("constructorul", "građevinac"),
    ("arhitecți", "arhitekti"),
    ("Arhitecți", "Arhitecti"),
    ("arhitect", "arhitekt"),
    ("Arhitect", "Arhitect"),
    ("investitori", "investitori"),
    ("Investitori", "Investitori"),
    ("investitor", "investitor"),
    ("Investitor", "Investitor"),
    ("dezvoltator", "investitor"),
    ("Dezvoltator", "Investitor"),
    ("dezvoltatorul", "investitor"),
    ("testimoniale", "svjedočanstva"),
    ("Testimoniale", "Svjedočanstva"),
    ("testimonial", "svjedočanstvo"),
    ("economii", "uštede"),
    ("Economii", "Uštede"),
    ("economie", "ušteda"),
    ("Economie", "Ušteda"),
    ("facturi", "računi"),
    ("Facturi", "Računi"),
    ("factură", "račun"),
    ("Factură", "Račun"),
    ("facturile", "račune"),
    ("încălzire", "grijanje"),
    ("Încălzire", "Grijanje"),
    ("încălzirii", "grijanja"),
    ("energie", "energija"),
    ("Energie", "Energija"),
    ("energiei", "energije"),
    ("energetică", "energetska"),
    ("energetice", "energetske"),
    ("pereți", "zidovi"),
    ("Pereți", "Zidovi"),
    ("pereții", "zidovi"),
    ("perete", "zid"),
    ("Perete", "Zid"),
    ("planșee", "podovi"),
    ("Planșee", "Planșee"),  # keep if not matched - fix
    ("planșeu", "pod"),
    ("acoperiș", "krov"),
    ("Acoperiș", "Krov"),
    ("acoperișul", "krov"),
    ("cofraj", "oplata"),
    ("Cofraj", "Oplata"),
    ("cofraje", "oplata"),
    ("prefabricate", "prefabrikovani"),
    ("prefabricat", "prefabrikovano"),
    ("prefabricate", "prefabrikovane"),
    ("panouri", "paneli"),
    ("Panouri", "Paneli"),
    ("panou", "panel"),
    ("Panou", "Panel"),
    ("panourilor", "panela"),
    ("cărămidă", "cigla"),
    ("Cărămidă", "Cigla"),
    ("cărămizii", "cigle"),
    ("cărămidă", "cigla"),
    ("caramidă", "cigla"),
    ("ofertă", "ponuda"),
    ("Ofertă", "Ponuda"),
    ("oferta", "ponuda"),
    ("gratuită", "besplatna"),
    ("gratuit", "besplatno"),
    ("Gratuit", "Besplatno"),
    ("certificare", "certifikacija"),
    ("Certificare", "Certifikacija"),
    ("certificat", "certificirano"),
    ("certificată", "certificirana"),
    ("certificați", "certificirani"),
    ("certificatul", "certifikat"),
    ("garanție", "garancija"),
    ("Garanție", "Garancija"),
    ("garanția", "garancija"),
    ("fabrică", "fabrika"),
    ("Fabrică", "Fabrika"),
    ("fabrici", "fabrike"),
    ("Fabrici", "Fabrike"),
    ("fabricii", "fabrike"),
    ("fabricat", "proizvedeno"),
    ("Fabricat", "Proizvedeno"),
    ("fabricată", "proizvedena"),
    ("izolație", "izolacija"),
    ("Izolație", "Izolacija"),
    ("izolația", "izolacija"),
    ("izolație", "izolacija"),
    ("termică", "termička"),
    ("termice", "termičke"),
    ("termici", "termički"),
    ("șantier", "gradilište"),
    ("Șantier", "Gradilište"),
    ("șantierul", "gradilište"),
    ("montaj", "montaža"),
    ("Montaj", "Montaža"),
    ("montajul", "montažu"),
    ("montează", "montira"),
    ("montat", "montiran"),
    ("execuție", "izvođenje"),
    ("Execuție", "Izvođenje"),
    ("execuția", "izvođenje"),
    ("săptămâni", "sedmice"),
    ("Săptămâni", "Sedmice"),
    ("săptămână", "sedmica"),
    ("Săptămâna", "Sedmica"),
    ("săptămânilor", "sedmica"),
    ("luni", "mjeseci"),
    ("Luni", "Mjeseci"),
    ("lună", "mjesec"),
    ("Lună", "Mjesec"),
    ("ani", "godina"),
    ("Ani", "Godina"),
    ("an", "godina"),
    ("An", "Godina"),
    ("anul", "godina"),
    ("anilor", "godina"),
    ("preț", "cijena"),
    ("Preț", "Cijena"),
    ("prețul", "cijenu"),
    ("prețuri", "cijene"),
    ("cost", "trošak"),
    ("Cost", "Trošak"),
    ("costuri", "troškovi"),
    ("costul", "trošak"),
    ("comparație", "poređenje"),
    ("Comparație", "Poređenje"),
    ("comparativ", "uporedni"),
    ("avantaje", "prednosti"),
    ("Avantaje", "Prednosti"),
    ("avantaj", "prednost"),
    ("performanță", "performanse"),
    ("Performanță", "Performanse"),
    ("performanțe", "performanse"),
    ("calitate", "kvalitet"),
    ("Calitate", "Kvalitet"),
    ("durabilitate", "trajnost"),
    ("Durabilitate", "Trajnost"),
    ("sustenabilitate", "održivost"),
    ("Sustenabilitate", "Održivost"),
    ("sustenabil", "održivo"),
    ("ecologic", "ekološki"),
    ("Ecologic", "Ekološki"),
    ("fundații", "temelji"),
    ("Fundații", "Temelji"),
    ("fundație", "temelj"),
    ("fațadă", "fasada"),
    ("Fațadă", "Fasada"),
    ("fațade", "fasade"),
    ("ferestre", "prozori"),
    ("Ferestre", "Prozori"),
    ("fereastră", "prozor"),
    ("scări", "stepenice"),
    ("Scări", "Stepenice"),
    ("scară", "stepenice"),
    ("uși", "vrata"),
    ("Uși", "Vrata"),
    ("suprafață", "površina"),
    ("Suprafață", "Površina"),
    ("suprafața", "površina"),
    ("suprafețe", "površine"),
    ("locație", "lokacija"),
    ("Locație", "Lokacija"),
    ("locația", "lokacija"),
    ("România", "Rumunija"),
    ("Franța", "Francuska"),
    ("Italia", "Italija"),
    ("Spania", "Španija"),
    ("Belgia", "Belgija"),
    ("Irlanda", "Irska"),
    ("Elveția", "Švicarska"),
    ("Germania", "Njemačka"),
    ("Austria", "Austrija"),
    ("Regatul Unit", "Ujedinjeno Kraljevstvo"),
    ("dumneavoastră", "vas"),
    ("dvs.", "vas"),
    ("Dumneavoastră", "Vi"),
    ("noastră", "naša"),
    ("noastre", "naše"),
    ("noștri", "naši"),
    ("nostru", "naš"),
    ("Nostru", "Naš"),
    ("noi", "mi"),
    ("Noi", "Mi"),
    ("suntem", "smo"),
    ("Suntem", "Smo"),
    ("sunt", "su"),
    ("Sunt", "Su"),
    ("este", "je"),
    ("Este", "Je"),
    ("ești", "ste"),
    ("aveți", "imate"),
    ("Aveți", "Imate"),
    ("avem", "imamo"),
    ("Avem", "Imamo"),
    ("pentru", "za"),
    ("Pentru", "Za"),
    ("fără", "bez"),
    ("Fără", "Bez"),
    ("cu", "sa"),
    ("Cu", "Sa"),
    ("și", "i"),
    ("Și", "I"),
    ("sau", "ili"),
    ("Sau", "Ili"),
    ("mai", "više"),
    ("Mai", "Više"),
    ("mult", "više"),
    ("Mult", "Više"),
    ("foarte", "vrlo"),
    ("Foarte", "Vrlo"),
    ("tot", "sve"),
    ("Tot", "Sve"),
    ("toate", "sve"),
    ("Toate", "Sve"),
    ("toți", "svi"),
    ("Toți", "Svi"),
    ("fiecare", "svaki"),
    ("Fiecare", "Svaki"),
    ("primul", "prvi"),
    ("prima", "prva"),
    ("ultimul", "posljednji"),
    ("cum", "kako"),
    ("Cum", "Kako"),
    ("de ce", "zašto"),
    ("De ce", "Zašto"),
    ("când", "kada"),
    ("Când", "Kada"),
    ("unde", "gdje"),
    ("Unde", "Gdje"),
    ("cine", "ko"),
    ("Cine", "Ko"),
    ("ce", "šta"),
    ("Ce", "Šta"),
    ("care", "koji"),
    ("Care", "Koji"),
    ("acest", "ovaj"),
    ("Acest", "Ovaj"),
    ("această", "ova"),
    ("Această", "Ova"),
    ("aceste", "ove"),
    ("Aceste", "Ove"),
    ("acestea", "ove"),
    ("detalii", "detalji"),
    ("Detalii", "Detalji"),
    ("constructive", "konstruktivni"),
    ("constructiv", "konstruktivni"),
    ("fișe", "listovi"),
    ("fișă", "list"),
    ("Fișă", "List"),
    ("ghid", "vodič"),
    ("Ghid", "Vodič"),
    ("articole", "članci"),
    ("Articol", "Članak"),
    ("întrebări", "pitanja"),
    ("Întrebări", "Pitanja"),
    ("întrebare", "pitanje"),
    ("Întrebare", "Pitanje"),
    ("răspunsuri", "odgovori"),
    ("Răspunsuri", "Odgovori"),
    ("răspuns", "odgovor"),
    ("Răspuns", "Odgovor"),
    ("companie", "kompanija"),
    ("Companie", "Kompanija"),
    ("compania", "kompanija"),
    ("viziune", "vizija"),
    ("Viziune", "Vizija"),
    ("misiune", "misija"),
    ("Misiune", "Misija"),
    ("fondator", "osnivač"),
    ("Fondator", "Osnivač"),
    ("fondatori", "osnivači"),
    ("echipa", "tim"),
    ("Echipa", "Tim"),
    ("echipei", "tima"),
    ("brevet", "patent"),
    ("Brevet", "Patent"),
    ("brevetat", "patentiran"),
    ("brevetată", "patentirana"),
    ("brevetate", "patentirane"),
    ("sistem", "sistem"),
    ("Sistem", "Sistem"),
    ("sistemul", "sistem"),
    ("produs", "proizvod"),
    ("Produs", "Proizvod"),
    ("produse", "proizvodi"),
    ("Produse", "Proizvodi"),
    ("soluție", "rješenje"),
    ("Soluție", "Rješenje"),
    ("soluții", "rješenja"),
    ("Soluții", "Rješenja"),
    ("clădire", "zgrada"),
    ("Clădire", "Zgrada"),
    ("clădiri", "zgrade"),
    ("locuință", "stan"),
    ("locuințe", "stanovi"),
    ("apartament", "stan"),
    ("vilă", "vila"),
    ("Vilă", "Vila"),
    ("vile", "vile"),
    ("ansamblu", "kompleks"),
    ("Ansamblu", "Kompleks"),
    ("ansambluri", "kompleksi"),
    ("investiție", "investicija"),
    ("Investiție", "Investicija"),
    ("partener", "partner"),
    ("Partener", "Partner"),
    ("parteneri", "partneri"),
    ("Parteneri", "Partneri"),
    ("parteneriat", "partnerstvo"),
    ("Parteneriat", "Partnerstvo"),
    ("antreprenor", "preduzetnik"),
    ("Antreprenor", "Preduzetnik"),
    ("inginer", "inženjer"),
    ("Inginer", "Inženjer"),
    ("ingineri", "inženjeri"),
    ("Ingineri", "Inženjeri"),
    ("client", "klijent"),
    ("Client", "Klijent"),
    ("clienți", "klijenti"),
    ("Clienți", "Klijenti"),
    ("formular", "formular"),
    ("Formular", "Formular"),
    ("mesaj", "poruka"),
    ("Mesaj", "Poruka"),
    ("nume", "ime"),
    ("Nume", "Ime"),
    ("telefon", "telefon"),
    ("Telefon", "Telefon"),
    ("adresă", "adresa"),
    ("Adresă", "Adresa"),
    ("oraș", "grad"),
    ("Oraș", "Grad"),
    ("orașul", "grad"),
    ("țară", "zemlja"),
    ("Țară", "Zemlja"),
    ("țări", "zemlje"),
    ("mulțumim", "hvala"),
    ("Mulțumim", "Hvala"),
    ("mulțumesc", "hvala"),
    ("eroare", "greška"),
    ("Eroare", "Greška"),
    ("descarcă", "preuzmite"),
    ("Descarcă", "Preuzmite"),
    ("descărcare", "preuzimanje"),
    ("Descărcări", "Preuzimanja"),
    ("documentație", "dokumentacija"),
    ("Documentație", "Dokumentacija"),
    ("specificații", "specifikacije"),
    ("Specificații", "Specifikacije"),
    ("tehnic", "tehnički"),
    ("Tehnic", "Tehnički"),
    ("tehnice", "tehničke"),
    ("tehnică", "tehnička"),
    ("contactați", "kontaktirajte"),
    ("Contactați", "Kontaktirajte"),
    ("contactați-ne", "kontaktirajte nas"),
    ("Contactați-ne", "Kontaktirajte nas"),
    ("aflați", "saznajte"),
    ("Aflați", "Saznajte"),
    ("află", "saznaj"),
    ("Află", "Saznaj"),
    ("citește", "pročitaj"),
    ("Citește", "Pročitaj"),
    ("vezi", "pogledaj"),
    ("Vezi", "Pogledaj"),
    ("vedeți", "vidite"),
    ("Vedeți", "Vidite"),
    ("trimiteți", "pošaljite"),
    ("Trimiteți", "Pošaljite"),
    ("trimite", "pošalji"),
    ("Trimite", "Pošalji"),
    ("selectați", "odaberite"),
    ("Selectați", "Odaberite"),
    ("selectează", "odaberi"),
    ("casă", "kuća"),
    ("Casă", "Kuća"),
    ("case", "kuće"),
    ("Case", "Kuće"),
    ("casei", "kuće"),
    ("casa", "kuća"),
    ("Casa", "Kuća"),
    ("proiect", "projekat"),
    ("Proiect", "Projekat"),
    ("proiecte", "projekti"),
    ("Proiecte", "Projekti"),
    ("proiectul", "projekat"),
    ("proiectului", "projekta"),
    ("proiecte", "projekte"),
    ("devino", "postanite"),
    ("Devino", "Postanite"),
    ("despre", "o"),
    ("Despre", "O"),
    ("resurse", "resursi"),
    ("Resurse", "Resursi"),
    ("contact", "kontakt"),
    ("Contact", "Kontakt"),
    ("termeni", "uslovi"),
    ("Termeni", "Uslovi"),
    ("confidențialitate", "privatnost"),
    ("Confidențialitate", "Privatnost"),
    ("mențiuni", "napomene"),
    ("Mențiuni", "Napomene"),
    ("legale", "pravne"),
    ("Legale", "Pravne"),
    ("cookie", "kolačić"),
    ("Cookie", "Kolačić"),
    ("cookies", "kolačići"),
    ("Cookies", "Kolačići"),
]

# Fix planșee
for i, (a, b) in enumerate(WORD_PAIRS):
    if a == "Planșee":
        WORD_PAIRS[i] = ("planșee", "podovi")
        WORD_PAIRS.insert(i, ("Planșee", "Podovi"))


def wb_replace(text: str, old: str, new: str) -> str:
    if " " in old or "—" in old or "·" in old:
        return text.replace(old, new)
    return re.sub(r"(?<![\wăâîșțĂÂÎȘȚ])" + re.escape(old) + r"(?![\wăâîșțĂÂÎȘȚ])", new, text)


def translate_block(text: str) -> str:
    for ro, cnr in sorted(WORD_PAIRS, key=lambda x: -len(x[0])):
        text = wb_replace(text, ro, cnr)
    return text


def process(text: str) -> str:
    parts = re.split(r"(<script[\s\S]*?</script>|<style[\s\S]*?</style>)", text, flags=re.I)
    return "".join(p if i % 2 else translate_block(p) for i, p in enumerate(parts))


def main():
    for html in sorted(ROOT.rglob("*.html")):
        t = html.read_text(encoding="utf-8")
        n = process(t)
        if n != t:
            html.write_text(n, encoding="utf-8")
    print("Applied word-boundary RO→CNR pass")

    # Update fr_to_cnr with word pairs for count
    fr_path = Path(__file__).resolve().parent / "translations/fr_to_cnr.json"
    data = json.loads(fr_path.read_text(encoding="utf-8"))
    for ro, cnr in WORD_PAIRS:
        if ro not in data:
            data[ro] = cnr
    fr_path.write_text(json.dumps(dict(sorted(data.items())), ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"fr_to_cnr now {len(data)} pairs")


if __name__ == "__main__":
    main()
