#!/usr/bin/env python3
"""Second pass: fix Italian/French hybrid visible text in ES focus files."""
from pathlib import Path

BASE = Path("countries/es")

FILES = {
    "para/propietarios/index.html",
    "para/arquitectos/index.html",
    "para/constructores/index.html",
    "productos/forjados-pbk/index.html",
    "proyectos/conjunto-lyon/index.html",
    "polistibrick-mercury-style.html",
}

# Order matters: longer / more specific strings first
REPLACEMENTS = [
    # --- Shared ---
    ("Contattaci", "Contáctenos"),
    ("Vedi tutti i progetti realizzati", "Ver todos los proyectos realizados"),
    ("Vedi la scheda", "Ver la ficha"),
    ("PDF certificato", "PDF certificado"),
    ("PDF ufficiale", "PDF oficial"),
    ("Catalogo accessori", "Catálogo de accesorios"),
    ("Famiglie parametriche", "Familias paramétricas"),
    ("Oggetti parametrici", "Objetos paramétricos"),
    ("Tutti i software", "Todos los programas"),
    ("Dettagli costruttivi", "Detalles constructivos"),
    ("Per studi tecnici", "Para estudios técnicos"),
    ("specifiche pronte da incollare", "especificaciones listas para insertar"),
    ("Polistibrick come cassaforma Eurocode 2", "Polistibrick como encofrado Eurocode 2"),
    ("Nota metodologica", "Nota metodológica"),
    ("Pareti", "Muros"),
    ("Solai", "Forjados"),
    ("Tetto", "Tejado"),
    ("Scegli il tuo prossimo passo", "Elija su siguiente paso"),
    ("Scopri il programma", "Descubra el programa"),
    ("Accedi all'Espacio Pro", "Acceda al Espacio Pro"),
    ("a tua disposizione", "a su disposición"),
    ("Ciò che", "Lo que"),
    ("davvero", "de verdad"),
    ("in base al tuo obiettivo", "según su objetivo"),
    ("Scegli", "Elija"),
    ("Stesso metodo calcolo, stessa messa in opera — adatti solo lo spessore dell'EPS in base al livello aislamiento previsto per tu proyecto.",
     "Mismo método de cálculo, misma puesta en obra — solo adapta el espesor del EPS según el nivel de aislamiento previsto para su proyecto."),
    ("Per progetti che mirano alla conformità normativa RE2020. Tutti i vantaggi Polistibrick (A1 fuoco, acustica 52 dB, idrofugo, antisísmico).",
     "Para proyectos que buscan la conformidad normativa RE2020. Todas las ventajas Polistibrick (A1 fuego, acústica 52 dB, hidrófugo, antisísmico)."),
    ("Vedi i dettagli →", "Ver los detalles →"),
    ("Contattaci</a>", "Contáctenos</a>"),
    ("Richiesta documentazione", "Solicitud de documentación"),
    ("Richiesta documentazione tecnica", "Solicitud de documentación técnica"),

    # --- propietarios ---
    ("Proprietari", "Propietarios"),
    ("Sappiamo cosa ti", "Sabemos lo que"),
    ("« E se tra 10 anni mi pentissi della mia scelta? »", "« ¿Y si dentro de 10 años me arrepiento de mi elección? »"),
    ("Abbiamo una", "Tenemos una"),
    ("È proprio per questo che Polistibrick è un'<strong>assicurazione contro l'inflazione energetica</strong>.",
     "Precisamente por eso Polistibrick es un <strong>seguro contra la inflación energética</strong>."),
    ("Polistibrick è una <strong>struttura in cemento armato classica</strong> — qualsiasi muratore, idraulico o elettricista può intervenire. L'isolante EPS non si degrada e la struttura non richiede manutenzione specifica.",
     "Polistibrick es una <strong>estructura de hormigón armado clásica</strong> — cualquier albañil, fontanero o electricista puede intervenir. El aislamiento EPS no se degrada y la estructura no requiere mantenimiento específico."),
    ("Qué cambia per te", "Lo que cambia para usted"),
    ("ogni giorno.", "cada día.</em>"),
    ("<h2>Concretamente, <em>cada día.</em></h2>", "<h2>En concreto, <em>cada día.</em></h2>"),
    ("Bolletta energetica", "Factura energética"),
    ("Silenzio, sicurezza, serenità", "Silencio, seguridad, serenidad"),
    ("Su casa protege a su familia de todo", "Su casa protege a su familia de todo"),
    ("Mai muffa", "Sin moho"),
    ("L'EPS a celle chiuse non assorbe acqua. I tuoi muri restano asciutti, i tuoi figli respirano aria sana, nessun problema di umidità tra 10 anni.",
     "El EPS de células cerradas no absorbe agua. Sus muros permanecen secos, sus hijos respiran aire sano, sin problemas de humedad dentro de 10 años."),
    ("L'inerzia termica del cemento + l'EPS mantengono una temperatura costante. Niente colpi di freddo in inverno, niente ondate di caldo in estate. Comfort totale.",
     "La inercia térmica del hormigón + el EPS mantienen una temperatura constante. Sin golpes de frío en invierno, sin olas de calor en verano. Confort total."),
    ("Calculadora dei risparmi", "Calculadora de ahorros"),
    ("Quanto la tua casa ti farà", "Cuánto le hará ahorrar su casa"),
    ("Indica la superficie della tua futura casa. Calcoliamo la tua factura annuale di calefacción con Polistibrick MBK 300 vs una casa classica RE2020.",
     "Indique la superficie de su futura casa. Calculamos su factura anual de calefacción con Polistibrick MBK 300 frente a una casa clásica RE2020."),
    ("Superficie abitabile della tua casa:", "Superficie habitable de su casa:"),
    ("di calefacción all'anno", "de calefacción al año"),
    ("Minimo legale RE2020", "Mínimo legal RE2020"),
    ("Risparmi <strong", "Ahorra <strong"),
    ("In 25 anni: <strong id=\"total-savings\">22 500 €</strong> di risparmio",
     "En 25 años: <strong id=\"total-savings\">22 500 €</strong> de ahorro"),
    ("Calcolo basato sul prezzo medio dell'energia in Francia 2025 (0,15 €/kWh, mix gas + elettricità). Consumo Polistibrick MBK 300 = 15 kWh/m²/an per il calefacción (standard Passivhaus, certificato CSTB). Consumo mattone classico = 55 kWh/m²/an (minimo legale RE2020). Polistibrick propone 3 spessori (MBK 210 / 270 / 300) — l'architetto sceglie in base al tuo progetto. I valori esatti sono calcolati nel tuo preventivo personalizzato.",
     "Cálculo basado en el precio medio de la energía en España 2025 (0,15 €/kWh, mix gas + electricidad). Consumo Polistibrick MBK 300 = 15 kWh/m²/año para calefacción (estándar Passivhaus, certificado CSTB). Consumo ladrillo clásico = 55 kWh/m²/año (mínimo legal RE2020). Polistibrick ofrece 3 espesores (MBK 210 / 270 / 300) — el arquitecto elige según su proyecto. Los valores exactos se calculan en su presupuesto personalizado."),
    ("Polistibrick vs gli altri", "Polistibrick frente a los demás"),
    ("Costo totale ottimale", "Coste total óptimo"),
    ("Leggermente più costoso del mattone in costruzione, molto meno costoso da vivere. In 25 anni: il más económico.",
     "Ligeramente más caro que el ladrillo en construcción, mucho más barato de habitar. En 25 años: el más económico."),
    ("4-5 mesi in mattone", "4-5 meses en ladrillo"),
    ("Ti trasferisci", "Se muda"),
    ("Classico passif", "Clásico pasivo"),
    ("Ossatura legno", "Estructura madera"),
    ("Classico</div>", "Clásico</div>"),
    (">Sì</span>", ">Sí</span>"),
    ("Integrato</span>", "Integrado</span>"),
    ("Nessuno</span>", "Ninguno</span>"),
    ("Eccellente</span>", "Excelente</span>"),
    ("Bassosa</span>", "Baja</span>"),
    ("Buona</span>", "Buena</span>"),
    ("mestieri</span>", "oficios</span>"),
    ("4-5 mesi</span>", "4-5 meses</span>"),
    ("5-6 mesi</span>", "5-6 meses</span>"),
    ("Stampata nel pannello", "Moldeada en el panel"),
    ("A1 (incombustibile)", "A1 (incombustible)"),
    ("B-s2 (combustibile)", "B-s2 (combustible)"),
    ("Nessunoe absorption", "Sin absorción"),
    ("Rischio putrefazione", "Riesgo de putrefacción"),
    ("Basso</span>", "Bajo</span>"),
    ("Molto alto</span>", "Muy alto</span>"),
    ("Massimo</span>", "Máximo</span>"),
    ("Minimo</span>", "Mínimo</span>"),
    ("Risparmi in 25 anni", "Ahorros en 25 años"),
    ("Per il <strong>dettaglio completo</strong>", "Para el <strong>detalle completo</strong>"),
    ("Case Polistibrick", "Casas Polistibrick"),
    ("Ecco le ultime.", "He aquí las más recientes.</em>"),
    ("Architettura moderna su R+1, zona residenziale premium vicino a Parigi. Pareti Polistibrick MBK 300, prestazione Passivhaus certificata, consegna estate 2025.",
     "Arquitectura moderna en R+1, zona residencial premium cerca de París. Muros Polistibrick MBK 300, rendimiento Passivhaus certificado, entrega verano 2025."),
    ("abitabili", "habitables"),
    ("2 livelli", "2 niveles"),
    ("Vedi il progetto", "Ver el proyecto"),
    ("Precedente", "Anterior"),
    ("Successivo", "Siguiente"),
    ("Vedi tutte le case costruite", "Ver todas las casas construidas"),
    ("nel tuo interesse.", "en su interés.</em>"),
    ("tutto il materiale necessario.", "todo el material necesario.</em>"),
    ("nel tuo interesse.</strong>", "en su interés.</strong>"),
    ("come una cassaforma classica.", "como un encofrado clásico.</em>"),
    ("Polistibrick è lo stesso cemento armato, ma gettato in una <strong>cassaforma termoisolante</strong>",
     "Polistibrick es el mismo hormigón armado, vertido en un <strong>encofrado termoaislante</strong>"),
    ("Con il tuo studio tecnico", "Con su estudio técnico"),
    ("Dialoguemos <em>con il tuo studio tecnico.</em>", "Dialoguemos <em>con su estudio técnico.</em>"),
    ("Se il tuo studio tecnico ha domande, entriamo in contatto con lui — <strong>nel tuo interesse</strong>. Gli spieghiamo chiaramente che Polistibrick è una cassaforma classica: vi si monta l'armatura, vi si getta il cemento. Da non confondere con le <strong>casseforme \"tipo Lego\"</strong>",
     "Si su estudio técnico tiene preguntas, contactamos con él — <strong>en su interés</strong>. Le explicamos claramente que Polistibrick es un encofrado clásico: se monta la armadura, se vierte el hormigón. No confundir con los <strong>encofrados \"tipo Lego\"</strong>"),
    ("Se nonostante tutto il tuo architetto rifiuta di collaborare nel tuo interesse</strong>",
     "Si a pesar de todo su arquitecto se niega a colaborar en su interés</strong>"),
    ("Le vere domande <em>che ti poni.</em>", "Las preguntas reales <em>que se hace.</em>"),
    ("Il polistirolo è ecologico?", "¿El poliestireno es ecológico?"),
    ("L'EPS (polistirolo espanso) è <strong>composto al 90% di aria</strong> e al 10% di polistirolo. È <strong>100% riciclabile</strong> a fine vita e non emette gas nocivi. Nel ciclo vita completo (50 anni), ha un'impronta di carbonio inferiore all'ossatura in legno perché evita decenni di calefacción. Il nostro rapporto LCA è disponibile su richiesta.",
     "El EPS (poliestireno expandido) está <strong>compuesto al 90% de aire</strong> y al 10% de poliestireno. Es <strong>100% reciclable</strong> al final de su vida útil y no emite gases nocivos. En el ciclo de vida completo (50 años), tiene una huella de carbono inferior a la estructura de madera porque evita décadas de calefacción. Nuestro informe LCA está disponible bajo solicitud."),
    ("RE2020 — il cemento non è vietato?", "RE2020 — ¿está prohibido el cemento?"),
    ("No. RE2020 fissa <strong>objetivos de carbono</strong> che Polistibrick raggiunge ampiamente grazie alle sue eccezionali prestazioni energetiche. Una simulazione tipo per il tuo progetto è disponibile. La voce \"cemento vietato\" è falsa — RE2020 penalizza semplicemente il cemento standard non isolato.",
     "No. RE2020 fija <strong>objetivos de carbono</strong> que Polistibrick alcanza ampliamente gracias a su excepcional rendimiento energético. Una simulación tipo para su proyecto está disponible. La idea de \"cemento prohibido\" es falsa — RE2020 simplemente penaliza el cemento estándar no aislado."),
    ("Quanto tempo per costruire la mia casa?", "¿Cuánto tiempo para construir mi casa?"),
    ("La struttura portante richiede <strong>4-6 semanas</strong> per una casa di 150-200 m² (vs 4-5 mesi in mattone classico). In totale, ti trasferisci in <strong>5-7 mesi</strong> (in base alle finiture e al permesso). È 2-3 volte più veloce di una construcción clásica.",
     "La estructura portante requiere <strong>4-6 semanas</strong> para una casa de 150-200 m² (frente a 4-5 meses en ladrillo clásico). En total, se muda en <strong>5-7 meses</strong> (según acabados y permisos). Es 2-3 veces más rápido que una construcción clásica."),
    ("E se volessi modificare la mia casa tra 10 anni?", "¿Y si quisiera modificar mi casa dentro de 10 años?"),
    ("Polistibrick è una <strong>struttura in cemento armato classica</strong>. Las modificaciones",
     "Polistibrick es una <strong>estructura de hormigón armado clásica</strong>. Las modificaciones"),
    ("Sì. Polistibrick è il <strong>cuore strutturale</strong> della tua casa — scegli la finitura esterna (intonaco, pietra, mattone di facciata, rivestimento in legno, ecc.) e interna (cartongesso, gesso, pittura). Non vedrai mai il cemento né l'EPS. La casa assomiglia a ciò che desideri: provenzale, contemporanea, tradizionale.",
     "Sí. Polistibrick es el <strong>núcleo estructural</strong> de su casa — elija el acabado exterior (revoco, piedra, ladrillo de fachada, revestimiento de madera, etc.) e interior (pladur, yeso, pintura). Nunca verá el hormigón ni el EPS. La casa se parece a lo que desee: provenzal, contemporánea, tradicional."),
    ("Come ottenere il finanziamento per questo sovrapprezzo?", "¿Cómo obtener financiación para este sobreprecio?"),
    ("Una casa pasiva es <strong>idonea all'eco-PTZ fino a 50.000 €</strong> (prestito a tasso zero, 15 anni). Diverse banche offrono anche <strong>prestiti verdi</strong> a tasso preferenziale. Il tuo consulente bancario tiene conto dei risparmi energetici per aumentare la tua capacità di mutuo.",
     "Una casa pasiva es <strong>idónea para el eco-préstamo hasta 50.000 €</strong> (préstamo a tipo cero, 15 años). Varios bancos ofrecen también <strong>préstamos verdes</strong> a tipo preferencial. Su asesor bancario tiene en cuenta los ahorros energéticos para aumentar su capacidad de hipoteca."),
    ("Chi è responsabile se qualcosa non va?", "¿Quién es responsable si algo sale mal?"),
    ("Il tuo <strong>costruttore certificato Polistibrick</strong>", "Su <strong>constructor certificado Polistibrick</strong>"),
    ("Stai scoprendo", "Está descubriendo"),
    ("Stai confrontando", "Está comparando"),
    ("Calcola il tuo progetto", "Calcule su proyecto"),
    ("Sei pronto", "Está listo"),
    ("Parlaci direttamente", "Hable con nosotros directamente"),
    ("'it-IT'", "'es-ES'"),
    ("Vai alla casa ", "Ir a la casa "),

    # --- arquitectos ---
    ("Para arquitectos e studi tecnici · Polistibrick — Sistema ICF in cemento armato",
     "Para arquitectos y estudios técnicos · Polistibrick — Sistema ICF de hormigón armado"),
    ("Polistibrick per architetti e studi tecnici: cassaforma classica per cemento armato, calcoli Eurocode 2 standard, libreria CAD/Revit, supporto tecnico dedicato, da RE2020 a Passiv+.",
     "Polistibrick para arquitectos y estudios técnicos: encofrado clásico para hormigón armado, cálculos Eurocode 2 estándar, biblioteca CAD/Revit, soporte técnico dedicado, de RE2020 a Passiv+."),
    ("Para arquitectos e studi tecnici", "Para arquitectos y estudios técnicos"),
    ("Calcola come sempre.", "Calcule como siempre.</em>"),
    ("Polistibrick è una <strong>cassaforma classica per cemento armato</strong>.",
     "Polistibrick es un <strong>encofrado clásico para hormigón armado</strong>."),
    ("con gli ICF classici.", "con los ICF clásicos.</em>"),
    ("Abbiamo creato Polistibrick per risolvere le 4 frizioni che impediscono ad architetti e studi tecnici di adottare un sistema ICF.",
     "Creamos Polistibrick para resolver las 4 fricciones que impiden a arquitectos y estudios técnicos adoptar un sistema ICF."),
    ("Polistibrick è una <strong>encofrado perdido para hormigón armado clásico</strong>. Mantieni i tuoi calcoli Eurocode 2 abituali. Trasmissione dei carichi, dimensionamento armature, verifiche ELU/ELS — esattamente come in qualsiasi progetto in cemento.",
     "Polistibrick es un <strong>encofrado perdido para hormigón armado clásico</strong>. Mantenga sus cálculos Eurocode 2 habituales. Transmisión de cargas, dimensionamiento de armaduras, verificaciones ELU/ELS — exactamente como en cualquier proyecto de hormigón."),
    ("Polistibrick proporciona <strong>biblioteca completa Revit + ArchiCAD + IFC + DWG</strong> per ogni prodotto (MBK 210/270/300, PBK, TBK). Integrazione diretta nel tuo progetto, senza modellazione manuale.",
     "Polistibrick proporciona <strong>biblioteca completa Revit + ArchiCAD + IFC + DWG</strong> para cada producto (MBK 210/270/300, PBK, TBK). Integración directa en su proyecto, sin modelado manual."),
    ("Il nostro <strong>Equipo técnico Polistibrick</strong>", "Nuestro <strong>equipo técnico Polistibrick</strong>"),
    ("I tuoi 3 vantaggi Polistibrick", "Sus 3 ventajas Polistibrick"),
    ("para ti.", "para usted.</em>"),
    ("Libertà <em>total de diseño.</em>", "Libertad <em>total de diseño.</em>"),
    ("3 niveles de rendimiento in base al tuo obiettivo: MBK 210 per RE2020 standard, MBK 270 per passivo, MBK 300 per passivo premium. Scegli in base al progetto.",
     "3 niveles de rendimiento según su objetivo: MBK 210 para RE2020 estándar, MBK 270 para pasivo, MBK 300 para pasivo premium. Elija según el proyecto."),
    ("in base al tuo obiettivo.", "según su objetivo.</em>"),
    ("parete 38 cm", "muro 38 cm"),
    ("parete 42 cm", "muro 42 cm"),
    ("parete 47 cm", "muro 47 cm"),
    ("Tetti isolanti", "Tejados aislantes"),
    ("Ciò che altri architetti <em>hanno progettato.</em>", "Lo que otros arquitectos <em>han diseñado.</em>"),
    ("Casa d'architetto contemporanea con sbalzo, realizzata con Polistibrick",
     "Casa de arquitecto contemporánea con voladizo, realizada con Polistibrick"),
    ("Villa contemporanea Île-de-France", "Villa contemporánea Île-de-France"),
    ("Un ingegnere Polistibrick", "Un ingeniero Polistibrick"),
    ("con Polistibrick.", "con Polistibrick.</em>"),
    ("CCTP — specifiche pronte da incollare", "CCTP — especificaciones listas para insertar"),

    # --- constructores ---
    ("Polistibrick per costruttori: sistema 5-in-1 = margini hasta el 50% (una squadra = 5 squadre), struttura portante 4-6 semanas, formazione certificante gratuita, lead trasmessi. Diventa Costruttore Certificato Polistibrick.",
     "Polistibrick para constructores: sistema 5-en-1 = márgenes hasta el 50% (un equipo = 5 oficios), estructura portante 4-6 semanas, formación certificante gratuita, leads transmitidos. Conviértase en Constructor Certificado Polistibrick."),
    ("Sai posare il cartongesso? <br><em>Sabe construir con Polistibrick.</em>",
     "¿Sabe colocar pladur? <br><em>Sabe construir con Polistibrick.</em>"),
    ("È una <strong>cassaforma classica</strong>: si misura, si taglia, si fissa — esattamente come qualsiasi altro sistema di cassaforma. L'unico vero imperativo in cantiere: <strong>essere precisi nelle misure</strong> e non tagliare il pannello 5 cm troppo corto. Il resto è solo posa guidata.",
     "Es un <strong>encofrado clásico</strong>: se mide, se corta, se fija — exactamente como cualquier otro sistema de encofrado. El único imperativo real en obra: <strong>ser preciso en las medidas</strong> y no cortar el panel 5 cm demasiado corto. El resto es solo montaje guiado."),
    ("una sola squadra svolge il lavoro 5 mestieri", "un solo equipo realiza el trabajo de 5 oficios"),
    ("impermeabilizzazione", "impermeabilización"),
    ("I tuoi margini operativi possono raggiungere il", "Sus márgenes operativos pueden alcanzar el"),
    ("Cantiere Polistibrick: getto del cemento in un lotto case",
     "Obra Polistibrick: vertido de hormigón en un lote de casas"),
    ("Le tue preoccupazioni in cantiere", "Sus preocupaciones en obra"),
    ("Ciò che ti trattiene dall'adottare <em>un nuovo sistema.</em>",
     "Lo que le frena de adoptar <em>un nuevo sistema.</em>"),
    ("« Temo perdere denaro mentre la mia squadra impara. »",
     "« Temo perder dinero mientras mi equipo aprende. »"),
    ("Formación técnica de <strong>2-3 giorni offerta in fabbrica</strong>",
     "Formación técnica de <strong>2-3 días ofrecida en fábrica</strong>"),
    ("Ti <strong>trasmettiamo lead qualificati</strong> da architetti e privati nel tuopartemento. Benefici inoltre del co-branding sui nostri supporti regionali.",
     "Le <strong>transmitimos leads cualificados</strong> de arquitectos y particulares en su departamento. Además se beneficia del co-branding en nuestros soportes regionales."),
    ("Qué cambia <em>per le tue performance finanziarie.</em>",
     "Qué cambia <em>en su rendimiento financiero.</em>"),
    ("Margini <em>hasta el 50%</em>", "Márgenes <em>hasta el 50%</em>"),
    ("Un'esecuzione 2-3 volte più veloce della muratura tradizionale. Concateni più progetti nell'anno senza aumentare la dimensione delle tue squadre.",
     "Una ejecución 2-3 veces más rápida que la mampostería tradicional. Encadena más proyectos al año sin aumentar el tamaño de sus equipos."),
    ("Zero sinistri, <em>zero stress</em>", "Cero siniestros, <em>cero estrés</em>"),
    ("La solida tecnologia del cemento armato gettato in una cassaforma isolante calibrata in fabbrica. I rischi di errori di taglio e difetti termici sono neutralizzati.",
     "La sólida tecnología del hormigón armado vertido en un encofrado aislante calibrado en fábrica. Los riesgos de errores de corte y defectos térmicos quedan neutralizados."),
    ("Diventa un <em>Costruttore Certificato Polistibrick.</em>",
     "Conviértase en <em>Constructor Certificado Polistibrick.</em>"),
    ("Una partnership focalizzata sulla crescita delle competenze delle tue squadre e sull'apporto nuovi mercati.",
     "Una colaboración centrada en el crecimiento de las competencias de sus equipos y en la apertura de nuevos mercados."),
    ("Formación certificada <em>offerta</em>", "Formación certificada <em>ofrecida</em>"),
    ("2-3 giorni intensivi nelle nostre fabbriche di produzione. Pratica reale di montaggio e taglio dei pannelli. Recepción di una <strong>certificazione ufficiale costruttore</strong>.",
     "2-3 días intensivos en nuestras fábricas de producción. Práctica real de montaje y corte de paneles. Recepción de una <strong>certificación oficial de constructor</strong>."),
    ("Supporto <em>sui tuoi cantieri</em>", "Soporte <em>en sus obras</em>"),
    ("Un tecnico applicazione ti accompagna durante la prima messa in opera sul tuo cantiere per validare il layout e il getto del cemento.",
     "Un técnico de aplicación le acompaña durante la primera puesta en obra en su obra para validar el montaje y el vertido de hormigón."),
    ("Co-branding <em>regionale</em>", "Co-branding <em>regional</em>"),
    ("Valorizzazione dei tuoi cantieri sui nostri supporti di comunicazione nazionali per consolidare la tua reputazione di costruttore passivo premium.",
     "Valorización de sus obras en nuestros soportes de comunicación nacionales para consolidar su reputación de constructor pasivo premium."),
    ("Beneficia di sconti commerciali dedicati e tempi di approvvigionamento riservati per garantire la redditività dei tuoi preventivi.",
     "Se beneficia de descuentos comerciales dedicados y plazos de suministro reservados para garantizar la rentabilidad de sus presupuestos."),
    ("I tuoi ordini in fabbrica sono trattati in flusso prioritario per garantirti la consegna dei colli secondo il tuo planning preciso cantiere.",
     "Sus pedidos en fábrica se tratan con prioridad para garantizarle la entrega de los paquetes según su planificación exacta de obra."),
    ("Il percorso partnership", "El recorrido de colaboración"),
    ("Compila il nostro modulo partner rapido. Il nostro servizio tecnico valida le tue competenze.",
     "Complete nuestro formulario de socio rápido. Nuestro servicio técnico valida sus competencias."),
    ("Entro 48 ore", "En 48 horas"),
    ("1 giornata", "1 jornada"),
    ("2-3 giorni", "2-3 días"),
    ("Formazione pratica ai metodi di layout, puntellamento e getto con i nostri formatori di cantiere.",
     "Formación práctica en métodos de montaje, apuntalamiento y vertido con nuestros formadores de obra."),
    ("Primera obra", "Primera obra"),
    ("Avvia i tuoi lavori con tranquillità grazie alla presenza del nostro ingegnere di applicazione.",
     "Inicie sus trabajos con tranquilidad gracias a la presencia de nuestro ingeniero de aplicación."),
    ("Supporto Pro", "Soporte Pro"),
    ("All'inizio, la squadra aveva qualche dubbio sull'apprendimento un nuovo sistema di blocchi. Tuttavia, il supporto del loro tecnico sul nostro primo cantiere ha sbloccato tutto. Il guadagno tempo è enorme, le finiture impeccabili e i clienti entusiasti.",
     "Al principio, el equipo tenía dudas sobre aprender un nuevo sistema de bloques. Sin embargo, el soporte de su técnico en nuestra primera obra lo desbloqueó todo. La ganancia de tiempo es enorme, los acabados impecables y los clientes entusiastas."),
    ("Direttore Lavori · Bâti-Innov SAS (Auvergne-Rhône-Alpes)",
     "Director de obra · Bâti-Innov SAS (Auvergne-Rhône-Alpes)"),
    ("benefíciese de leads cualificados", "benefíciese de leads cualificados"),

    # --- forjados-pbk ---
    ("Campate di <em>9 m sin vigas.</em>", "Luces de <em>9 m sin vigas.</em>"),
    ("PBK è il sistema prefabbricato solai che supporta campate standard fino a 9 metri senza travi a vista. Combina polistirolo, fibrocemento e hormigón armato per uno sfasamento termico",
     "PBK es el sistema prefabricado de forjados que soporta luces estándar de hasta 9 metros sin vigas a la vista. Combina poliestireno, fibrocemento y hormigón armado para un desfase térmico"),
    ("Sezione solaio PBK", "Sección forjado PBK"),
    ("Sfasamento termico", "Desfase térmico"),
    ("Campata massima", "Luz máxima"),
    ("Valore U (W/m²K)", "Valor U (W/m²K)"),
    ("Valore U", "Valor U"),
    ("Tre materiali, <em>un unico solaio.</em>", "Tres materiales, <em>un único forjado.</em>"),
    ("PBK riunisce in un unico pannello prefabbricato ciò che richiedeva 3 squadre diverse in cantiere:",
     "PBK reúne en un único panel prefabricado lo que requería 3 equipos distintos en obra:"),
    ("Hormigón armado strutturale", "Hormigón armado estructural"),
    ("gettato nelle nervature interne dopo la posa, campata fino a 9 m",
     "vertido en las nervaduras internas tras la colocación, luz de hasta 9 m"),
    ("arriva in cantiere pronto da posare, non da assemblare",
     "llega a obra listo para colocar, no para ensamblar"),
    ("3 varianti predefinite", "3 variantes predefinidas"),
    ("Per ogni <em>campata.</em>", "Para cada <em>luz.</em>"),
    ("Compatto", "Compacto"),
    ("Campata max.", "Luz máx."),
    ("★ Consigliato — PBK 250", "★ Recomendado — PBK 250"),
    ("L'equilibrio perfetto: campata generosa, ottimo sfasamento termico, costo ottimale.",
     "El equilibrio perfecto: luz generosa, excelente desfase térmico, coste óptimo."),
    ("Premium Grande Campata", "Premium gran luz"),
    ("Campate massime, prestazioni termiche massime. Per spazi aperti e grandi volumi.",
     "Luces máximas, máximo rendimiento térmico. Para espacios abiertos y grandes volúmenes."),
    ("Su misura su richiesta · senza costi aggiuntivi",
     "A medida bajo pedido · sin costes adicionales"),
    ("Perché PBK", "Por qué PBK"),
    ("Il calore delle 14:00 raggiunge l'interno solo alle 00:00, quando fuori fa già fresco. Climatizzazione ridotta al minimo.",
     "El calor de las 14:00 llega al interior solo a las 00:00, cuando fuera ya hace fresco. Climatización reducida al mínimo."),
    ("3× più leggero un solaio in hormigón tradizionale. Fondazioni più semplici, trasporto più economico, movimentazione più sicura.",
     "3× más ligero que un forjado de hormigón tradicional. Cimentaciones más simples, transporte más económico, manipulación más segura."),
    ("La combinazione EPS + fibrocemento assorbe i rumori da calpestio e i rumori aerei tra i piani. Silencio garantizado.",
     "La combinación EPS + fibrocemento absorbe los ruidos de impacto y los ruidos aéreos entre plantas. Silencio garantizado."),
    ("I dati esatti per tu proyecto.", "Los datos exactos para su proyecto."),
    ("Famiglia BIM (Revit)", "Familia BIM (Revit)"),
    ("Il sistema completo", "El sistema completo"),
    ("Cassaforma isolante a perdere con 3 modelli (210/270/300). Pareti passive A+++ in un unico getto.",
     "Encofrado aislante perdido con 3 modelos (210/270/300). Muros pasivos A+++ en un único vertido."),
    ("Pareti MBK", "Muros MBK"),
    ("Tetto TBK", "Tejado TBK"),
    ("Sistema Passivhaus pronto in fabbrica. Campate di 9 m, U=0,13, solo 22 kg/m².",
     "Sistema Passivhaus listo en fábrica. Luces de 9 m, U=0,13, solo 22 kg/m²."),
    ("Invia il progetto della tua casa e ricevi un preventivo esatto per il PBK adatto al tuo progetto — gratuito, senza impegno.",
     "Envíe el proyecto de su casa y reciba un presupuesto exacto para el PBK adecuado a su proyecto — gratuito, sin compromiso."),

    # --- conjunto-lyon ---
    ("Caso studio Polistibrick: complesso residenziale di 24 unidades × 120 m² a Lione, certificato Passivhaus. Construcción in 6 mesi con MBK 270.",
     "Caso de estudio Polistibrick: conjunto residencial de 24 unidades × 120 m² en Lyon, certificado Passivhaus. Construcción en 6 meses con MBK 270."),
    ("Il promotore [Nom de la Société] cercava un sistema che combinasse velocità, prestazioni Passivhaus e margine di profitto. Ha scelto Polistibrick MBK 270 per le 24 unidades. Las 24 casas se entregaron en 6 meses en total. Todas certificadas Passivhaus al primer intento. Vendute in 4 semanas con un premio del 18% sopra la media del settore.",
     "El promotor [Nombre de la empresa] buscaba un sistema que combinara velocidad, rendimiento Passivhaus y margen de beneficio. Eligió Polistibrick MBK 270 para las 24 unidades. Las 24 casas se entregaron en 6 meses en total. Todas certificadas Passivhaus al primer intento. Vendidas en 4 semanas con una prima del 18% sobre la media del sector."),
    ("Complesso Lione", "Conjunto Lyon"),
    ("24<small> unità</small>", "24<small> unidades</small>"),
    ("Alloggi consegnati", "Viviendas entregadas"),
    ("Certificati Passivhaus", "Certificados Passivhaus"),
    ("Prima sobre el precio de venta", "Prima sobre el precio de venta"),
    ("[Nom du directeur]</strong>Direttore di progetto · [Nom de la Société] · Lione, FR",
     "[Nombre del director]</strong>Director de proyecto · [Nombre de la empresa] · Lyon, FR"),
    ("Informazioni sul progetto", "Información del proyecto"),
    ("tempi</strong> (6 meses frente a 14 mesi con ladrillo), <strong>costo</strong> (apenas un 5% por encima del ladrillo, pero con rendimiento A+++), <strong>prevedibilità</strong> (pannelli prefabbricati, nessuna sorpresa in cantiere).",
     "plazos</strong> (6 meses frente a 14 meses con ladrillo), <strong>coste</strong> (apenas un 5% por encima del ladrillo, pero con rendimiento A+++), <strong>previsibilidad</strong> (paneles prefabricados, sin sorpresas en obra)."),
    ("Certificazione", "Certificación"),
    ("Inizio", "Inicio"),
    ("Gennaio 2024", "Enero 2024"),
    ("45<small> €/mesi</small>", "45<small> €/mes</small>"),
    ("Cronologia di esecuzione", "Cronología de ejecución"),
    ("consegna delle chiavi.", "entrega de llaves.</em>"),
    ("elettricità, idraulica per tutte le unità.", "electricidad, fontanería para todas las unidades."),
    ("Galleria fotografica", "Galería fotográfica"),
    ("Come si è svolto, <em>paso a paso.</em>", "Cómo transcurrió, <em>paso a paso.</em>"),
    ("Tutte <span", "Todas <span"),
    ("Rendering architettonico del complesso finale.", "Render arquitectónico del conjunto final."),
    ("[Foto: Rendering del progetto]", "[Foto: Render del proyecto]"),
    ("Lavori di scavo per le 24 unidades.", "Trabajos de excavación para las 24 unidades."),
    ("Montaggio coordinato su 2 unità simultaneamente.", "Montaje coordinado en 2 unidades simultáneamente."),
    ("Pareti MBK 270 montate su più case.", "Muros MBK 270 montados en varias casas."),
    ("Tetti TBK per le 24 unidades.", "Tejados TBK para las 24 unidades."),
    ("[Foto: Mese 2 — Moduli 1+2]", "[Foto: Mes 2 — Módulos 1+2]"),
    ("[Foto: Mese 3 — Moduli 3+4]", "[Foto: Mes 3 — Módulos 3+4]"),
    ("Test Blower Door sul primo modulo.", "Test Blower Door en el primer módulo."),
    ("Recepción tecnica con le autorità locali.", "Recepción técnica con las autoridades locales."),
    ("[Foto: Complesso completato]", "[Foto: Conjunto completado]"),
    ("[Foto: Unità modello]", "[Foto: Unidad modelo]"),
    ("Via principale del complesso.", "Vía principal del conjunto."),
    ("Interno modello — soggiorno open space.", "Interior modelo — salón diáfano."),
    ("[Foto: Certificato ufficiale]", "[Foto: Certificado oficial]"),
    ("Recepción delle chiavi ai primi occupanti.", "Entrega de llaves a los primeros ocupantes."),
    ("Occupanti insediati dopo 6 mesi.", "Ocupantes instalados tras 6 meses."),
    ("Chiudi", "Cerrar"),
    ("Immagine precedente", "Imagen anterior"),
    ("Immagine successiva", "Imagen siguiente"),
    ("Calculadora di costo", "Calculadora de costes"),
    ("Galleria fotografica\"", "Galería fotográfica\""),

    # --- mercury-style ---
    ("Sistema ICF completo per casa A+++.", "Sistema ICF completo para casa A+++."),
    ("Risorse", "Recursos"),
    ("Contact</a>", "Contacto</a>"),
    ("Calculadora risparmi", "Calculadora de ahorros"),
    ("3 materiali</strong>", "3 materiales</strong>"),
    ("5 team — 15 persone", "5 equipos — 15 personas"),
    ("9 materiali</strong>", "9 materiales</strong>"),
    ("Cantiere Polistibrick: getto hormigón in un lotto case",
     "Obra Polistibrick: vertido de hormigón en un lote de casas"),
    ("ROI massimo. <em>Rischio minimo.</em>", "ROI máximo. <em>Riesgo mínimo.</em>"),
    ("Costruttore", "Constructor"),
    ("Architetto", "Arquitecto"),
    ("Proprietario", "Propietario"),
    ("Promotore", "Promotor"),
    ("Hanno costruito con Polistibrick — <em>hablan de ello.</em>",
     "Han construido con Polistibrick — <em>hablan de ello.</em>"),
    ("Vedi tutte le recensioni →", "Ver todas las reseñas →"),
    ("3 mesi fa", "hace 3 meses"),
    ("5 mesi fa", "hace 5 meses"),
    ("2 mesi fa", "hace 2 meses"),
    ("Certificato e riconosciuto a livello internazionale", "Certificado y reconocido a nivel internacional"),
    ("Il sistema ICF brevettato per case passive premium, sin facturas energetiche. Fabbricato nell'UE.",
     "El sistema ICF patentado para casas pasivas premium, sin facturas energéticas. Fabricado en la UE."),
    ("Mappa d'Europa: i paesi di presenza Polistibrick", "Mapa de Europa: países de presencia Polistibrick"),
    ("3 modelli premium (210/270/300) più produzione su ordinazione senza costi aggiuntivi. L'unico ICF con questa garanzia.",
     "3 modelos premium (210/270/300) más producción bajo pedido sin costes adicionales. El único ICF con esta garantía."),
    ("Finito <em>5 en 1.</em>", "Acabado <em>5 en 1.</em>"),
    ("Fuoco A1 · Antisismico", "Fuego A1 · Antisísmico"),
    ("di luce · 65 kg/m² · Acustica ≥ 52 dB", "de luz · 65 kg/m² · Acústica ≥ 52 dB"),
    ("La cubierta más performante de su categoría.", "La cubierta con mejor rendimiento de su categoría."),
    ("Montaggio", "Montaje"),
    ("Fasi di posa", "Fases de montaje"),
    ("Cassero assemblato con puntellatura laterale", "Encofrado ensamblado con apuntalamiento lateral"),
    ("Cassero", "Encofrado"),
    ("Pareti EPS erette e fissate con puntellatura laterale in legno sulla fondazione. Senza malta, senza perdite di aislamiento.",
     "Muros EPS erigidos y fijados con apuntalamiento lateral de madera sobre la cimentación. Sin mortero, sin pérdidas de aislamiento."),
    ("Solaio PBK montato", "Forjado PBK montado"),
    ("Solaio", "Forjado"),
    ("Armadura acciaio-hormigón sul solaio", "Armadura acero-hormigón en el forjado"),
    ("Vedi tutto il montaggio", "Ver todo el montaje"),
    ("Contatto rapido", "Contacto rápido"),
    ("Invia email", "Enviar email"),
    ("Invia la mia recensione →", "Enviar mi reseña →"),
    ("Scegli…", "Elija…"),
    ("aria-label=\"Chiudi\"", "aria-label=\"Cerrar\""),
]


def apply_replacements(text: str) -> tuple[str, int]:
    count = 0
    for old, new in REPLACEMENTS:
        if old in text:
            n = text.count(old)
            text = text.replace(old, new)
            count += n
    return text, count


def main():
    total = 0
    per_file = {}
    for rel in sorted(FILES):
        path = BASE / rel
        original = path.read_text(encoding="utf-8")
        updated, n = apply_replacements(original)
        if updated != original:
            path.write_text(updated, encoding="utf-8")
        per_file[rel] = n
        total += n
        print(f"{rel}: {n} replacements")
    print(f"TOTAL: {total}")
    return total


if __name__ == "__main__":
    main()
